### ISSUE TITLE
Derivate Not Implemented Error

### ISSUE THREAD

**Issue by esaliya** [rusty1s/pytorch_sparse#10]
I am trying to use `spmm` with a sparse tensor that's coming from the result of `spspmm`. This produces the following error.

```
  File "/anaconda3/envs/hep/lib/python3.6/site-packages/torch_sparse/spmm.py", line 21, in spmm
    out = scatter_add(out, row, dim=0, dim_size=m)
  File "/anaconda3/envs/hep/lib/python3.6/site-packages/torch_scatter/add.py", line 73, in scatter_add
    return out.scatter_add_(dim, index, src)
RuntimeError: the derivative for 'index' is not implemented
```

I couldn't figure this out but I see `requires_grad=True` in the indices tensor of the `spspmm` output. Could this be the reason and is there a way to set it off?

**Comment by rusty1s** [comment]
Hi, the derivative wrt to index is not defined, and I am wondering which op requires a geadient of it. You can set if off by calling index.requires_grad_(False).

**Comment by esaliya** [comment]
This is what I tried doing as well, so before I call `spspmm` I do, `a_idxs.requires_grad = False` and `b_idxs.requires_grad = False`, where `a_idxs` and `b_idxs` are the two index vectors of the two sparse tensors. What surprises me is that the indexes tensor returned by `spspmm` has this flag set to `True`. I can't set it to `False` because the returned indexes tensor also has the `is_leaf` flag set to `False`.

**Comment by esaliya** [comment]
Adding to my previous reply, I noticed that if I do `detach().clone()` on the returned indexes tensor of `spspmm`,  that seems to take care of this problem. However, I don't know if that's efficient as I am doing a clone just get this working.

**Comment by rusty1s** [comment]
These seems to be a bug. I will fix it ASAP on Monday. Sorry for the inconveniences.

**Comment by rusty1s** [comment]
Fixed in current master. If you do not want to upgrade, a simple `detach()` on the index is enough, you do not need to clone it.
