### ISSUE TITLE
How to add an element to the diagonal

### ISSUE THREAD

**Issue by ldv1** [rusty1s/pytorch_sparse#100]
Hi,

I want to add a constant to the diagonal of a sparse matrix. Looking at [GCNConv](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py), I assume this is what `SparseTensor.fill_diag` does (it would be great if methods were documented).
With

```
import torch
from torch_sparse import SparseTensor
 
col = torch.tensor([1,1,5,0]).type(torch.long)
row = torch.tensor([2,5,3,0]).type(torch.long)
adj = SparseTensor(col=col, row=row)
A = adj.to_dense()
print(A)

```
I got as expected 

```
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.]])
```

Further
```
adj = SparseTensor.fill_diag(adj, 4.)
print(adj.to_dense())
```

returns

```
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 1.]])

```
So, the diagonal is filled with 1s, instead of 4s. What is wrong with my code?
Thanks for any help.

**Comment by rusty1s** [comment]
It will only fill the diagonal with values in case `value` is present in `adj`:
```python
col = torch.tensor([1,1,5,0]).type(torch.long)
row = torch.tensor([2,5,3,0]).type(torch.long)
value = torch.tensor([1, 1, 1, 1].type(torch.float)
adj = SparseTensor(col=col, row=row, value=value)
```

**Comment by ldv1** [comment]
Thanks for the prompt answer.
My code will then work with:
```

if not adj_t.has_value():
    adj = adj.fill_value(0.)
adj = SparseTensor.fill_diag(adj, 1234.)
print( adj.to_dense() )
```

So, I understand that `value` is sort of a placeholder. We first define the placeholder and then fill it.
May I ask why you opted for this strange construct, i.e. why  `fill_diag(adj,my_float)`, as the name implies, would not simply fill the diagonal elements with `my_float`?

What would be the simplest way to _add_ to the diagonal instead of filling?

**Comment by rusty1s** [comment]
I'm sorry for the lack of documentation :)

In general, `SparseTensor` supports two formats: One where we only care about connections (`value=None`), and one which is similar to any other sparse matrix library (`value!=None`). In case there exists no values, we simply want to add diagonal connections to the matrix.

There's no easy way yet to add diagonal entries to existing ones, since sum is currently not implemented.

**Comment by ldv1** [comment]
> There's no easy way yet to add diagonal entries to existing ones, since sum is currently not implemented

That's bad news. I wanted to extent SIGN to more general propagation matrices. For that I need to add to the diagonal of an adjacency matrix.

**Comment by rusty1s** [comment]
But for that, adding diagonal entries is sufficient, isn't it? No need to sum them up in case there already exists some.

**Comment by ldv1** [comment]
The idea is to define a continuum of propagation matrices. To make the problem more easily understandable, I will push a PR.

**Comment by ldv1** [comment]
We have a `set_diag` method. Is there a `get_diag`?

**Comment by rusty1s** [comment]
Getting diagonal entries is quite straightforward:
```python
row, col, value = A.coo()
diag_values = value[row == col]
```

**Comment by ldv1** [comment]
Thanks.
Why not a new function `set_diag` in diag.py ? That might be useful for others as well.

**Comment by rusty1s** [comment]
Just pushed `mat.get_diag()` to master, see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/diag.py#L96).

**Comment by ldv1** [comment]
Just what I needed. Thanks.

**Comment by ldv1** [comment]
Currently, we can only set the diagonal elements of a sparse matrix by specifying a scalar, right ? Would it be possible to specify a tensor instead ?

**Comment by rusty1s** [comment]
You can either fill with a scaler via `fill_diag` or with a tensor via `set_diag`.
