### ISSUE TITLE
OSError: /opt/conda/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev

### ISSUE THREAD

**Issue by yunxingluoyun** [rusty1s/pytorch_sparse#103]
Hi, using CUDA10.1 with pytorch 1.5.1 here.

 I try to migrate the virtual environment in Conda (to configure PYG) to another server that cannot be connected to the Internet. The torch is normal, but after the migration, the following error is reported when importing the PYG library:
OSError: /opt/conda/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev

**Comment by rusty1s** [comment]
This error is caused by a mismatch of PyTorch/CUDA versions. Please ensure that the PyTorch version and the CUDA version match with the ones of the external packages (`torch-sparse`, ...).
