### ISSUE TITLE
SPMM throws FPE for very sparse SparseTensor on CPU

### ISSUE THREAD

**Issue by MortezaRamezani** [rusty1s/pytorch_sparse#110]
I noticed when the `SparseTensor` is very sparse (density < 0.1%), the SPMM throws FPE on CPU, while the CUDA version is working fine. Here is a short example:

```python
import sys
import torch
from torch_sparse import SparseTensor
import scipy.sparse as sp

device = torch.device(sys.argv[1])
x = torch.rand(2000, 2000).to(device)
a = sp.rand(2000, 2000, density=0.0001, format='csr')
a = SparseTensor.from_scipy(a).type_as(torch.FloatTensor()).to(device)

b = a.spmm(x)
print(b.shape)
```

Running on CPU will result in:
![image](https://user-images.githubusercontent.com/2129613/104780708-2cc3e280-574f-11eb-8d25-fe93f11de84e.png)

While on GPU:
![image](https://user-images.githubusercontent.com/2129613/104780795-54b34600-574f-11eb-92c5-b166dba4bae0.png)

**Comment by MortezaRamezani** [comment]
The problem occurs because of [line](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/spmm_cpu.cpp#L60), as the denominator becomes zero for highly sparse matrix.

```c++
int64_t grain_size =
                at::internal::GRAIN_SIZE / (K * (col.numel() / M));
```

**Comment by rusty1s** [comment]
Good spot! Thanks a lot. This is now fixed in master.
