### ISSUE TITLE
PyTorch and torch_sparse were compiled with different CUDA

### ISSUE THREAD

**Issue by MDrance** [rusty1s/pytorch_sparse#117]
Hi,

As the title says, I'm having an issue where it seems that torch-sparse and torch are not using the same version. 
```
PyTorch has CUDA version 11.0 and torch_sparse has CUDA version 11.2
```
The thing is that I did everything from scratch a lot of time (re install CUDA, torch, torchgeom, etc...) following the doc every time and I really don't get why I'm still getting this error. 
I currently have this setup :
Running **pip list | grep torch**
```
torch                  1.7.1+cu110
torch-cluster          1.5.9
torch-geometric        1.6.3
torch-scatter          2.0.6
torch-sparse           0.6.8
torch-spline-conv      1.2.1
torchaudio             0.7.2
torchvision            0.8.2+cu110
```
Running **nvidia-smi**
```
CUDA Version: 11.0 
```

Running **nvcc -V**:
```
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

```
Running **python3.9 -c "import torch; print(torch.version.cuda)"**:
```
11.0
```
Running **python3.9 -c "import torch; print(torch.__version__)""**:
```
1.7.1+cu110
```
I really don't know where torch-sparse find a CUDA 11.2.

I tried everything I could find on the git Issues as well...

**Comment by rusty1s** [comment]
That is indeed weird. PyTorch seems to find a CUDA 11.2 version on your system.

You can get around this by pointing your system to the CUDA 11.0 installation provided by PyTorch, which is usually located in `{miniconda}/lib` (should contain files such as `libcusparse.so`) via:
```
export LD_LIBRARY_PATH={miniconda}/lib:$LD_LIBRARY_PATH
```

**Comment by MDrance** [comment]
Hi and thanks for your answer. 
I should have closed this issue as I found a way to make everything work this weekend. I had some really really strange bugs with Numba and LLVM, had to re-install everything...

Thanks again, for your answer and Pytorch-Geometric
