### ISSUE TITLE
'assert col.dtype == torch.long' error

### ISSUE THREAD

**Issue by calebchiam** [rusty1s/pytorch_sparse#119]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/14286996/110925074-9b4c9900-82d7-11eb-908a-4b20afb1326f.png">

I encountered this error while trying to use `torch_sparse.spspmm`, as shown below:

`edge_index, edge_weights = spspmm(edge_index, edge_weights, edge_index, edge_weights, N, N, N)`

where `edge_index` is an NxN Float32 SparseTensor and `edge_weights` is a Float32 1D tensor with length N.

Would you have any idea what the issue is? The data is from `ogbn-arxiv` and these are my package versions:
- torch==1.7.1
- torch-geometric==1.6.3
- torch-scatter==2.0.6
- torch-sparse==0.6.8

**Comment by calebchiam** [comment]
```
from torch_sparse import spspmm
dataset = PygNodePropPredDataset(name='ogbn-arxiv', root = 'dataset/', transform=T.ToSparseTensor())
data = dataset[0]
data.adj_t = data.adj_t.to_symmetric()
edge_idx = data.adj_t.to(device)
x = data.x.to(device)
y = data.y.to(device)
N = x.size(0)
edge_weights = x.new_ones(N)
spspmm(edge_idx, edge_weights, edge_idx, edge_weights, N, N, N)
```

Here is a minimal reproducible example.

**Comment by rusty1s** [comment]
`adj_t` is not the correct data type for inputting into `spspmm`. Alternatively, you can simply run:
```python
adj_t @ adj_t
```

**Comment by calebchiam** [comment]
Thanks for the help! I had mistaken `adj_t` for `edge_index` as you pointed out.
