### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_sparse.unique_cuda'

### ISSUE THREAD

**Issue by aikprot** [rusty1s/pytorch_sparse#12]
Hello everyone,

I would appreciate your help in the following issue Ι am having. Unfortunately previously raised related threads couldn't help me. 
Having installed successfully PyTorch Geometric and all dependencies, I tried to run the introduction example in a terminal. After typing "from torch_geometric.data import Data" I am getting 
ModuleNotFoundError: No module named 'torch_sparse.unique_cuda'. 
Any recommendations on what to do next? 

Thank you in advance for your help!

Here is a printscreen of what I am seeing: 
![issue_print_screen](https://user-images.githubusercontent.com/46448420/54442899-2d9d1f00-4748-11e9-9daa-032e788b648a.PNG)

**Comment by rusty1s** [comment]
As inidicated in the [installation guide](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html), this usually indicated that installation failed for `torch-sparse`. Please verify by running
```
$ git clone https://github.com/rusty1s/pytorch_sparse
$ cd pytorch_sparse
$ python setup.py install  # Check for CUDA compilation or link error.
$ python setup.py test  # Verify installation by running test suite.
```
and report back.

**Comment by aikprot** [comment]
Thank you for your respond. 
It seems to fail and I am getting this screen. 
![error2](https://user-images.githubusercontent.com/46448420/54515370-8517d680-4964-11e9-9ee1-a09e24016c1c.png)
Is there any other python/cuda/cudnn/pytorch/ versions you recommend for installation on Windows 10?
Thank you in advance for your help

**Comment by rusty1s** [comment]
Maybe @Konnsy can help?

**Comment by Fantasyyan** [comment]
Hi,I meet the same problem as you .

ModuleNotFoundError: No module named 'torch_sparse.unique_cuda'

Did you solved the problem ? Thank you very much!

**Comment by j4freeman** [comment]
I'm getting the same error, I seem to be able to install through setup.py fine but when I try to run the tests I get the following: 

![Capture](https://user-images.githubusercontent.com/8677991/58516796-2317f080-81a1-11e9-8ecd-65ba741ad05d.PNG)

Running windows 10 pytorch 1.1 and cuda 10.1.

**Comment by rezapci** [comment]
I have the same error, any solution yet?

**Comment by lihua213** [comment]
The error can be solved by "import torch" first!
for example:
import torch
from torch_sparse import spspmm
