### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by shxzhao** [rusty1s/pytorch_sparse#121]
When I install the torch_sparse by the command (pip uninstall torch-sparse && pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html), there is a error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhao/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

**Comment by rusty1s** [comment]
Closing this in favour of https://github.com/rusty1s/pytorch_geometric/issues/2304

**Comment by shxzhao** [comment]
Thanks for your reply! @rusty1s  I failed install the cpu version.But I succeed in installing the CUDA version.
