### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by devskroy1** [rusty1s/pytorch_sparse#127]
I am using torch-sparse version 0.6.8 as a dependency for a project I am working on.

However, I get the following error inside the `torch_sparse/__init__.py` file:
`torch.ops.load_library(importlib.machinery.PathFinder().find_spec(`
`AttributeError: 'NoneType' object has no attribute 'origin'`

It seems that the `find_spec()` call returns None.

I am running on CUDA on Ubuntu and using torch version 1.7.1 and torch-scatter version 2.0.5
Do you know how I can resolve this error?

Thanks

**Comment by rusty1s** [comment]
Have you seen https://github.com/rusty1s/pytorch_geometric/issues/2304? Can you check if the `*.so` files in the `torch_sparse` folder exist? 

You also may have multiple `torch-sparse` versions? Can you try to repeatedly uninstall them and install again?

**Comment by devskroy1** [comment]
Thanks for your reply.
I have now resolved the issue. The *.so files were getting created in the `torch_sparse` folder. The problem was that the cuda .so files weren't getting created. I had to change the `torch_sparse` and `torch_cluster` versions.
I don't believe I had multiple `torch_sparse` versions.

**Comment by Andrea-V** [comment]
@devskroy1 I am getting the same error. Which version of `torch_sparse` and `torch_cluster` did you end up installing?

**Comment by Juju-botu** [comment]
I will leave my 50 cents here, I tried other methods to solve this problem but then but just got other issues 😅
I solved them by updating to PyTorch 1.8.1 and CUDA to 11.1 (using Ubuntu 20.04). 
Here are the steps:
1. Update CUDA to the [latest version](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&=Ubuntu&target_version=20.04). NOTE: if you encounter problems with the CUDA installation, follow [this solution](https://forums.developer.nvidia.com/t/cuda-install-unmet-dependencies-cuda-depends-cuda-10-0-10-0-130-but-it-is-not-going-to-be-installed/66488/5) (basically purge the Nvidia drivers and reinstall them so to avoid problems with dependencies)
2. Install latest version of `torch` with `cuda` by running this (from [PyTorch webpage](https://pytorch.org/))
```
pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
```
3. Install `torch-geometric` and its dependencies this in your terminal (from the [PyTorch Geometric installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html)):
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
pip install torch-geometric
```

**Comment by JiayuanDing100** [comment]
> Thanks for your reply.
> I have now resolved the issue. The *.so files were getting created in the `torch_sparse` folder. The problem was that the cuda .so files weren't getting created. I had to change the `torch_sparse` and `torch_cluster` versions.
> I don't believe I had multiple `torch_sparse` versions.

actually i met with the same issue with you. In my case, *cpu.so file were getting created but no cuda .so files found. How did you. resolve. this problem?

**Comment by rusty1s** [comment]
Did you install the CUDA package, e.g. via `https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html`? Otherwise, you may try to install with the `--no-index` option, i.e.
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+{CUDA}.html
```

**Comment by KushajveerSingh** [comment]
I am also facing the same issue. My environment is
- python = 3.9.4
- pytorch = 1.8.1
- CUDA = 11.1
- torch_scatter = 2.0.6
- torch_sparse = 0.6.9
- torch_cluster = 1.5.9
- torch_geometric = 1.7.0

I installed the packages from pypi and I checked that I was installing using the pytorch 1.8.0 and CUDA 111 link. I tried to do `--no-index` install but I got the following error
```
ERROR: Could not find a version that satisfies the requirement torch-sparse
ERROR: No matching distribution found for torch-sparse
```
I checked that `torch.cuda.is_available()` returns `True`. The issue is `torch_sparse` is not compiling the cuda.so files. I checked by installing the packages from source (except pytorch) and the same error persists. I installed pytorch using the `conda` command and the version of cuda is `11.1.74`.

During the compilation process of `torch_sparse` it is building cpu packages but not building cuda packages. I can confirm that this error was not occurring with python 3.8 and pytorch 1.7 and cuda 10.

**Comment by rusty1s** [comment]
Yes, we currently do not provide Python 3.9 binaries. I will work on that.

I'm not sure if there is a difference between packages with different CUDA versions. You can check by downloading https://pytorch-geometric.com/whl/torch-1.8.0+cu111/torch_sparse-0.6.9-cp38-cp38-linux_x86_64.whl that it also contains the required `*_cuda.so` files.

I installed PyTorch from conda and `CUDA_HOME` is still set for me. Nonetheless, you can still force CUDA installation by running:
```
FORCE_CUDA=1 python setup.py install
```

**Comment by KushajveerSingh** [comment]
This is interesting. I checked with a clean miniconda installation also that `CUDA_HOME` was not set after installing pytorch (1.8.1) from conda. Maybe the driver on my machine is not working properly with `cudatoolkit` that is installed with conda or I am using a maxwell mobile GPU, that is pretty old for cuda 11.

But I got the `pytorch_geometric` working with cuda 10.2 so I am ok. There are not many features of cuda 11 that my gpu can use, so I am not missing on anything.

**Comment by sujedi** [comment]
> Thanks for your reply.
> I have now resolved the issue. The *.so files were getting created in the `torch_sparse` folder. The problem was that the cuda .so files weren't getting created. I had to change the `torch_sparse` and `torch_cluster` versions.
> I don't believe I had multiple `torch_sparse` versions.

I met the same problem and fixed it by installing cuda package. 
Check if '/usr/local/cuda-11.x' is existing. 
If you install 'cuda toolkit' in conda virtual env, you can't find it. (refer to below explanation)  

![image](https://user-images.githubusercontent.com/55679368/128280409-70ab70e5-4497-448e-a014-b69eaeb2b208.png)

My solution is:
1. install 'cuda toolkit 11.1' (not in conda virtual env)
2. install torch_geometric using below commands
   conda create -n XXX python=3.8
   conda activate XXX
   conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
   conda install pytorch-geometric -c rusty1s -c conda-forge

**Comment by daeunni** [comment]
> > Thanks for your reply.
> > I have now resolved the issue. The *.so files were getting created in the `torch_sparse` folder. The problem was that the cuda .so files weren't getting created. I had to change the `torch_sparse` and `torch_cluster` versions.
> > I don't believe I had multiple `torch_sparse` versions.
> 
> I met the same problem and fixed it by installing cuda package. Check if '/usr/local/cuda-11.x' is existing. If you only install 'cuda toolkit' in conda virtual env, you can't find it. (refer to below explanation)
> 
> ![image](https://user-images.githubusercontent.com/55679368/128280409-70ab70e5-4497-448e-a014-b69eaeb2b208.png)
> 
> My solution is:
> 
> 1. install 'cuda' (not in conda virtual env)
> 2. install torch_geometric in conda virtual env using below commands
>    conda create -n XXX python=3.8
>    conda activate XXX
>    conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
>    conda install pytorch-geometric -c rusty1s -c conda-forge

this is work for me. thanks :)

**Comment by omoju** [comment]
This issue has not been solved.

**Comment by twidatalla** [comment]
Hi all, currently experiencing this issue only when I run torch on GPU, but everything works fine. I usually use torch==1.12.1+cu116, but had to downgrade to torch==1.8.1+cu111 to be able to import torch_geometric on just CPU. This is the error I get when I try and import torch_geometric on GPU:

Python 3.8.2 (default, Jun  2 2020, 16:34:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.8.1+cu111'
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/widatall/cuda111/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/widatall/cuda111/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/widatall/cuda111/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/widatall/cuda111/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
>>>

I installed all packages as per PyTorch guidelines:

pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-geometric

In regard to the .so files, I am having the issue of only having *_cpu.so files and no *_cuda.so files in my torch_sparse, torch_scatter etc. directories in the site-packages/ directory of my venv. Any help on this would be greatly appreciated as I am currently trying to train a transformer+GCNN on just cpu...... which will be done when I'm 90 years old.

**Comment by rusty1s** [comment]
Please install via `--no-index` option for later PyTorch versions:
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
```

**Comment by na396** [comment]
I had the same issue, after spending day and days, finally the above solution works so far for me!
