### ISSUE TITLE
Using float16 and float32 for preprocessing author/institution features in MAG240M gives significantly different results

### ISSUE THREAD

**Issue by BarclayII** [rusty1s/pytorch_sparse#128]
Hi there,

When I poked around the [baseline RGNN code for OGB-MAG240M](https://github.com/snap-stanford/ogb/blob/master/examples/lsc/mag240m/rgnn.py), I found that the author features and institution features are precomputed using average of neighboring paper/author features.  However, the result of using float16 and float32 has a difference of as large as 0.1.

Basically I replaced the author/institution feature precomputation code
```python
inputs = torch.from_numpy(inputs)
outputs = adj_t.matmul(inputs, reduce='mean').numpy()
```
to
```python
inputs = torch.from_numpy(inputs.astype('float32'))
outputs = adj_t.matmul(inputs, reduce='mean').numpy().astype('float16')
```

And I compared the full feature matrix generated by two methods:
```python
f1 = np.memmap('/mnt/b/full_feat.npy', mode='r', dtype='float16').reshape(-1, 768)  # Generated by float16
f2 = np.memmap('/mnt/b/full_feat2.npy', mode='r', dtype='float16').reshape(-1, 768)  # Generated by float32

for i in range(dataset.num_papers, dataset.num_papers + dataset.num_authors + dataset.num_institutions):
    assert np.abs(f1[i] - f2[i]).max() < 0.1  # fails
```

I tried comparing against using numpy's float16, and I found that the result of using torch-sparse's float32 is indeed accurate but torch-sparse's float16 is not.
```python
ei_writes = dataset.edge_index('author', 'paper')
author_id = i - dataset.num_papers
paper_indices = ei_writes[1][ei_writes[0] == author_id]
pp = f1[paper_indices].mean(0)
np.abs(f1[i] - pp).max()
# 0.1758
np.abs(f2[i] - pp).max()
# 0.0
```

Any insights will be appreciated!

EDIT: I compiled torch-sparse from master commit 4d49d44.

**Comment by rusty1s** [comment]
Thanks for this issue. I'm pretty confident that `spmm` on `torch.half` works as expected, and that differences in output can solely be explained by half-precision accuracy.

In particular, there are only a few nodes/features for which the error is high. For me, the average error is `0.000017854` and median error is `0`. I guess that nodes with high feature error are highly-connected nodes, where summation of a lot of neighbors lead to the observed instabilities.

It is nonetheless good to be aware of this issue. If you find that `float32` pre-processing works better for you, please go for it :)
