### ISSUE TITLE
type problems reproducing spspmm example from readme

### ISSUE THREAD

**Issue by anhinga** [rusty1s/pytorch_sparse#13]
>>> from torch_sparse import spspmm
>>>
>>> indexA = torch.tensor([[0, 0, 1, 2, 2], [1, 2, 0, 0, 1]])
>>> valueA = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float)
>>>
>>> indexB = torch.tensor([[0, 2], [1, 0]])
>>> valueB = torch.tensor([2, 4], dtype=torch.float)
>>> indexC, valueC = spspmm(indexA, valueA, indexB, valueB, 3, 3, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 26, in spspmm
    return SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 32, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 68, in mm
    indexC, valueC = from_scipy(A.tocsr().dot(B.tocsr()).tocoo())
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 79, in from_scipy
    row, col, value = from_numpy(A.row), from_numpy(A.col), from_numpy(A.data)
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.

(Windows 10 CPU-only PyTorch installation.)

The other examples from README work ok, except that "coalesce" transposes value:

>>> from torch_sparse import coalesce
>>>
>>> index = torch.tensor([[1, 0, 1, 0, 2, 1],
...                       [0, 1, 1, 1, 0, 0]])
>>> value = torch.tensor([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]])
>>> index, value = coalesce(index, value, m=3, n=2)
>>> index
tensor([[0, 1, 1, 2],
        [1, 0, 1, 0]])
>>> value
tensor([[6, 8],
        [7, 9],
        [3, 4],
        [5, 6]])

**Comment by rusty1s** [comment]
The first issue seems Windows related. Tests work fine on Ubuntu. I will look into it. The coalesce call seems fine. What is your problem with it?

**Comment by anhinga** [comment]
Thanks...

"coalesce" is fine (I was just surprised that it formatted it differently from README, but it's not a problem).

**Comment by rusty1s** [comment]
Ok, i can fix that too :)

**Comment by anhinga** [comment]
:-)

ah, I see that I have SciPy 1.1.0. Do I need to upgrade it?

**Comment by anhinga** [comment]
(SciPy 1.1.0 is what the current Anaconda for Windows and Python 3.7 has as the default version, but the latest SciPy is SciPy 1.2.1.)

**Comment by rusty1s** [comment]
Can you check if this fixes the error?

**Comment by anhinga** [comment]
Looks like it's the same error:

(base) C:\Users\Fluid3>pip install --user scipy --upgrade
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/58/f0/d00c0e01e077da883f030af3ff5ce653a0e9e4786f83faa89a6e18c98612/scipy-1.2.1-cp37-cp37m-win_amd64.whl
Requirement already satisfied, skipping upgrade: numpy>=1.8.2 in c:\programdata\anaconda3\lib\site-packages (from scipy) (1.15.4)
Installing collected packages: scipy
Successfully installed scipy-1.2.1


(base) C:\Users\Fluid3>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.2.1'
>>> import torch
>>> import torch_sparse
>>> from torch_sparse import spmm
>>>
>>> index = torch.tensor([[0, 0, 1, 2, 2],
...                       [0, 2, 1, 0, 1]])
>>> value = torch.tensor([1, 2, 4, 1, 3], dtype=torch.float)
>>> matrix = torch.tensor([[1, 4], [2, 5], [3, 6]], dtype=torch.float)
>>>
>>> out = spmm(index, value, 3, matrix)
>>> out
tensor([[ 7., 16.],
        [ 8., 20.],
        [ 7., 19.]])
>>> from torch_sparse import spspmm
>>>
>>> indexA = torch.tensor([[0, 0, 1, 2, 2], [1, 2, 0, 0, 1]])
>>> valueA = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float)
>>>
>>> indexB = torch.tensor([[0, 2], [1, 0]])
>>> valueB = torch.tensor([2, 4], dtype=torch.float)
>>> indexC, valueC = spspmm(indexA, valueA, indexB, valueB, 3, 3, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 26, in spspmm
    return SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 32, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 68, in mm
    indexC, valueC = from_scipy(A.tocsr().dot(B.tocsr()).tocoo())
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 79, in from_scipy
    row, col, value = from_numpy(A.row), from_numpy(A.col), from_numpy(A.data)
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.

**Comment by anhinga** [comment]
(I double-checked by clearing the associated *.pyc file and by adding

```
import scipy

print("SciPy version: ", scipy.__version__)
```

to spspmm.py - it is now indeed using SciPy 1.2.1 with the same diagnostics.)

**Comment by anhinga** [comment]
(Further upgraded NumPy to 1.16.2 and PyTorch to 1.0.1, but the bug would not go away.)

**Comment by rusty1s** [comment]
Can you modify the source in `spspmm.py` and print the output of `A.row`, `A.col`, and `A.data` in line 80 before the `from_numpy` calls? I have actually no idea why it's not working and may need your help to fix this.

**Comment by anhinga** [comment]
Yes, this is what prints (superficially looks fine):

A.row:  [0 1 2]
A.col:  [0 1 1]
A.data:  [8. 6. 8.]

I do see that PyTorch's `from_numpy` has a long and tortured history in their issues, so it's the most likely suspect...

**Comment by anhinga** [comment]
Now with `dtype`:

A.row:  [0 1 2] int32
A.col:  [0 1 1] int32
A.data:  [8. 6. 8.] float32

But it is something pretty subtle. Interactively, similar integer arrays work fine, and it's only `A.row` and `A.col` which are broken, not `A.data`, e.g. replacing that assignment with

```
    value = from_numpy(A.data)
    col = from_numpy(A.col)
    row = from_numpy(A.row)
```

we obtain error in `from_numpy(A.col)`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 37, in spspmm
    return SpSpMM.apply(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 43, in forward
    indexC, valueC = mm(indexA, valueA, indexB, valueB, m, k, n)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 80, in mm
    indexC, valueC = from_scipy(C_scipy)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 95, in from_scipy
    col = from_numpy(A.col)
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.

**Comment by rusty1s** [comment]
Thank you. We should consider changing the dtype of row and col to int64 before calling `from_numpy`. Maybe this already solves the problem.

**Comment by anhinga** [comment]
Yes, this does work:

```
    value = from_numpy(A.data)
    a_col = A.col.astype("int64")
    col = from_numpy(a_col)
    a_row = A.row.astype("int64")
    row = from_numpy(a_row)
```

So, it is a possible fix.

**Comment by anhinga** [comment]
But, what's interesting, even this works:

```
    value = from_numpy(A.data)
    a_col = A.col.astype("int32")
    col = from_numpy(a_col)
    a_row = A.row.astype("int32")
    row = from_numpy(a_row)
```

So, something is strangely broken - a weird difference between the correct `int32` and something strange which they print as `numpy.int32`.

**Comment by anhinga** [comment]
So - thanks a lot!

I am not sure what's the correct "canonical fix" here should be, but it is possible to work with this software on Windows at the moment with this understanding...

**Comment by rusty1s** [comment]
Thank you. Indeed very strange, but good to know how to fix. Do you want to PR or shall I fix this issue?

**Comment by anhinga** [comment]
I should probably ask you to fix this. 

(You have much better feel for all the context involved here, in terms of making sure there is no performance degradation in other platforms, and that it still plays well in the machine learning contexts where you and other people are using `torch_sparse`. 

In this sense, I am a complete novice, as this is my first attempt to use `torch_sparse`...)

**Comment by rusty1s** [comment]
Fixed in master. Thank you for providing so much detailed feedback.
