### ISSUE TITLE
Sparse matri

### ISSUE THREAD

**Issue by YayangLi** [rusty1s/pytorch_sparse#130]
Hello rusty,
      The add function in this project seems could only processing addition between Sparse matrix and Dense matrix. What could I do if wants to add sparse with sparse?

**Comment by rusty1s** [comment]
We are working on it, see [here](https://github.com/rusty1s/pytorch_sparse/issues/113). At the moment, you should be able to directly utilize this code snippet.

**Comment by rusty1s** [comment]
This is actually already supported in master :)
