### ISSUE TITLE
Where is torch.ops.torch_sparse.spmm_sum?

### ISSUE THREAD

**Issue by mdanb** [rusty1s/pytorch_sparse#132]
I'm looking at the `spmm_sum` function from `torch-sparse` in `matmul.py`:

```
def spmm_sum(src: SparseTensor, other: torch.Tensor) -> torch.Tensor:
    rowptr, col, value = src.csr()

    row = src.storage._row
    csr2csc = src.storage._csr2csc
    colptr = src.storage._colptr

    if value is not None and value.requires_grad:
        row = src.storage.row()

    if other.requires_grad:
        row = src.storage.row()
        csr2csc = src.storage.csr2csc()
        colptr = src.storage.colptr()

    return torch.ops.torch_sparse.spmm_sum(row, rowptr, col, value, colptr,
                                           csr2csc, other)
```
I can't seem to find 
`torch.ops.torch_sparse.spmm_sum(row, rowptr, col, value, colptr, csr2csc, other)`
How can I access this function?

**Comment by rusty1s** [comment]
It's implemented in C++ and CUDA [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/spmm_cpu.cpp) and [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cuda/spmm_cuda.cu). It's loaded into PyTorch [here](https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/__init__.py#L14-L15).
