### ISSUE TITLE
Is there any implementation of index_select for SparseTensor idx ?

### ISSUE THREAD

**Issue by sandl99** [rusty1s/pytorch_sparse#136]
Hello everyone, 

I'm working with aggregation GNN. For my purpose, I want to aggregate all neighbor features to the center nodes, which don't use layer sampling like GraphSAGE (using fixed neighbors). So, I have faced how to build neighbors of center nodes from layer to layer. 

The original idea to build fixed neighbor :

1.  Build a matrix G which have sizes (num_nodes, num_neighbor_fix)
2. The neighbor of center nodes N (size=batch) in the first layer: G[N] (size =(batch, num_neighbor_fix)
3. The neighbor of center nodes N (size=batch) in the second layer: G[G[N]]].reshape(batch, -1) (size=(batch, num_neighbor^2))

Here is code for above idea

```
batch_size = v.shape[0]
entities = [v]                # v is a batch of center nodes, adj is a matrix (built as adjacency list, because  number of neighbor fixed)
for h in range(self.n_iter):
    neighbor_entities = torch.LongTensor(adj[entities[h]]).view((batch_size, -1)).to(self.device)
    entities.append(neighbor_entities)
```

So, if I want to aggregate all neighbor features, I have to use SparseTensor for matrix G. I looked up in pytorch_sparse library, and just found the function `index_select` supporting for  Tensor index. 
So Is the any implementation for it and if not, how can I implement this idea ?
Thank you for your reading!

**Comment by rusty1s** [comment]
Not sure if I understand you correctly, but `G[G[N]]` should just work fine using the `SparseTensor`.

**Comment by sandl99** [comment]
I tried indexing `SparseTensor` using `SparseTensor` but not work, it seems that indexing takes API from `index_select`
I am trying to reimplement `index_select` with `idx` parameter is `SparseTensor`.

**Comment by rusty1s** [comment]
Oh, yeah. I see, my bad. You can, of course, only index with `LongTensor`, so you could do something like:
```python
G = G[N]
_, col, _ = G.coo()  # neighbor indices
G = G[col]
```

**Comment by sandl99** [comment]
Oh, thank you. That's a great solution. 
I think my solution works too, It's not hard to implement `index_select` with `idx` parameters 1D 2D `SparseTensor`
