### ISSUE TITLE
segmentation fault when testing

### ISSUE THREAD

**Issue by by2101** [rusty1s/pytorch_sparse#14]
Hi, rusty1s,

I've install the pytorch_scatter in a conda virtual env. And I encoountered segmentation fault when testing.
I've checked version, cuda=10.0, torch=1.0.1.post2,gcc=7.3

Thank you!

**Comment by by2101** [comment]
I've checked, when running test function test_coalesce_max(), segmentation fault happens.
maybe it is because the op='max'
index, value = coalesce(index, value, m=3, n=2, op='max')

**Comment by by2101** [comment]
solved.

**Comment by rusty1s** [comment]
What did you do to solve?

**Comment by by2101** [comment]
> 
> 
> What did you do to solve?

I reinstalled torch-scatter.

I would like to record how to install these extensions in a conda virtual environment. It is a little bit more complex than common installation. 
1) create a enviroment: conda create -n my_env python=3; and enter it source activate my_env 
2) install gcc compiling tools with conda: conda install gcc_linux-64 gxx_linux-64
then the gcc is in ~/miniconda3/envs/my_env/bin/x86_64-conda_cos6-linux-gnu-gcc. add a soft symbol in the dir: 
ln -s x86_64-conda_cos6-linux-gnu-gcc gcc 
ln -s x86_64-conda_cos6-linux-gnu-g++ g++
3) install cuda development toolkit: conda install cudatoolkit-dev
3) install pytorch: conda install pytorch
4) install the extensions with source code:
python setup.py build;
python setup.py install
python setup.py test
