### ISSUE TITLE
Provide `metis` -included prebuilt wheels

### ISSUE THREAD

**Issue by bwdeng20** [rusty1s/pytorch_sparse#140]
Hi, Matthias

Could you please provide prebuilt pip wheels consisting of `metis` functionality? It really takes much time for users to build the whole `pytorch_sparse` from  source. Moreover, I have never built `torch_sparse` successfully on `windows` when `metis` is included.

**Comment by rusty1s** [comment]
`metis` is already included in the pre-built wheels. How did you try to install `torch-sparse`?

**Comment by bwdeng20** [comment]
I followed the `README` earlier which guides me to build from source. But I just did some experiments and found that I missed something. Thanks for your efforts!
