### ISSUE TITLE
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseDcsrgemm2'

### ISSUE THREAD

**Issue by Catriminal** [rusty1s/pytorch_sparse#144]
I tried to use pytorch model in my C++ code, and I have installed C++ extension of torch_sparse.
But when make my C++ code, I face the error like below:

```
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseDcsrgemm2_bufferSizeExt'
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseXcsrgemm2Nnz'
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseScsrgemm2_bufferSizeExt'
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseDcsrgemm2'
/usr/local/lib/libtorchsparse.so: undefined reference to `cusparseScsrgemm2'
```

So I think I should link cusparse library, but after add `-lcusparse` for nvcc to compile, it still get same error.
The command I compile is similar like below:

```
nvcc tigr/gcn_mask_for.o -o bin/gcn_mask_for -arch=sm_60 -lcublas -lcusparse -lcurand -std=c++14  -ltorch_cpu -ltorch -ltorchsparse -ltorchscatter -lc10 -lpthread -O3
```

Since I have no experience of pytorch jit, I cannot find any clue to solve this.
How can I handle this error?

**Comment by Catriminal** [comment]
It work when I put `-lcusparse` after `-ltorchsparse`. And thanks a lot.

**Comment by zhenyuzhouiu** [comment]
@Catriminal
Hey, How do you solve the problem? I meet the same problem when I torch_sparse for my C++ project.

error: /usr/local/torchsparse0.6.12/lib/libtorchsparse.so: undefined reference to `cusparseScsrgemm2_bufferSizeExt'
error: /usr/local/torchsparse0.6.12/lib/libtorchsparse.so: undefined reference to `cusparseDcsrgemm2_bufferSizeExt'
error: /usr/local/torchsparse0.6.12/lib/libtorchsparse.so: undefined reference to `cusparseXcsrgemm2Nnz'
error: /usr/local/torchsparse0.6.12/lib/libtorchsparse.so: undefined reference to `cusparseDcsrgemm2'
error: /usr/local/torchsparse0.6.12/lib/libtorchsparse.so: undefined reference to `cusparseScsrgemm2'
