### ISSUE TITLE
torch.jit.script -> Tensor (inferred) cannot be used as a tuple

### ISSUE THREAD

**Issue by slaweks17** [rusty1s/pytorch_sparse#146]
Hi.
I am trying to use pytorch_sparse (with Pytorch 1.8) in a module that is jitted, something like
cell = torch.jit.script(S2Layer(h_size, state_size)) 

But this fails:
Tensor (inferred) cannot be used as a tuple:
  File "C:\progs2\Anaconda3\envs\pytorch18\lib\site-packages\torch_sparse\spmm.py", line 20
    assert n == matrix.size(-2)
    row, col = index
               ~~~~~ <--- HERE

I tried the index to be a tensor
index_t=torch.tensor([row_indices,column_indices])
or tuple of tensors
indices =(torch.tensor(row_indices),torch.tensor(column_indices)) 
but neither option works.

Without jitting the code works.

**Comment by rusty1s** [comment]
I fixed it here :)

**Comment by slaweks17** [comment]
Thank you. 
I also needed to change the spmm declaration into 
def spmm(index, value, m: int, n: int, matrix):
