### ISSUE TITLE
Feature request: `spspmm` to multiply two sparse matrices with multi-dimensional values

### ISSUE THREAD

**Issue by JonnyTran** [rusty1s/pytorch_sparse#147]
Suppose I have two sparse COO matrices, A of size (m, k, D) and B of size (k, n, D), where D is the size for entries in the `edge_attr` vector. Currently, there's this check in place that assert D must be equal to 1
https://github.com/rusty1s/pytorch_sparse/blob/8d03163af730bdb7d7a115ce1f2e3627f036cb1a/csrc/cuda/spspmm_cuda.cu#L50

however, it would be really nice if `torch_sparse.spspmm` can have the capability to multiply two sparse matrices where D > 1. Will it ever be possible with the current cusparse implementation?

Code for what I want to do:
```python
A = SparseTensor(row=indexA[0], col=indexA[1], value=valueA, # valueA size (num_edges_A, num_edge_attrs)
                 sparse_sizes=(m, k), is_sorted=not coalesced)
B = SparseTensor(row=indexB[0], col=indexB[1], value=valueB, # valueB size (num_edges_B, num_edge_attrs)
                 sparse_sizes=(k, n), is_sorted=not coalesced)

C = torch_sparse.matmul(A, C)
```

**Comment by rusty1s** [comment]
Sadly, `cusparse` does not support this. I'm nonetheless curious on what you think how such a sparse-sparse matrix multiplication is defined. Is it equal to running a for-loop over each entry in the last dimension?

**Comment by JonnyTran** [comment]
Yes, I meant multiplying the edge attributes vector by entry-by-entry. The motivation for this is to support multiplying multi-head attention scores.

And yes, I was able to have a work-around by doing a for-loop for each entry in the `edge_attr` dimension, although it's a few times slower.

**Comment by rusty1s** [comment]
As `cusparse` does not support this, we probably need to do a for-loop internally as well :(

**Comment by JonnyTran** [comment]
Thanks Matthias!
