### ISSUE TITLE
Error while installing with pytorch 1.1

### ISSUE THREAD

**Issue by kshre** [rusty1s/pytorch_sparse#15]
This is just a tip for any one having trouble compiling torch_sparse with the current pytorch version 1.1.

I ran into errors when I tried to install this package with a pytorch installation 1.1 which disappeared when I uninstalled it and instead used pytorch version 1.0.

I can post the exact errors for reference.

**Comment by rusty1s** [comment]
Thank you. I fixed it for PyTorch 1.1.0 in current master and will craft a new release.
