### ISSUE TITLE
Regarding of torch_sparse, scatter install using pip

### ISSUE THREAD

**Issue by hmkim** [rusty1s/pytorch_sparse#150]
**My env..**
pytorch 1.7.0
cuda 10.1

If I try to install like this, I can't use the module normally.

```
pip install torch-scatter torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.1+cu101.html
```

But I installed successfully like this.

```
pip install https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl

pip install 
https://pytorch-geometric.com/whl/torch-1.7.0+cu101/torch_sparse-0.6.9-cp38-cp38-linux_x86_64.whl
```

This situation guess first command miss the whl file normally.

**Comment by rusty1s** [comment]
For past PyTorch versions it's always best to define exact version numbers of packages, as we only build new versions for the two latest PyTorch versions. In your case,
```
pip install torch-scatter==2.0.7 torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.7.1+cu101.html
```
should fix your issues.
