### ISSUE TITLE
Possibility of using SparseTensor as a parameter for a model

### ISSUE THREAD

**Issue by Filco306** [rusty1s/pytorch_sparse#151]
Hello, 

Thank you for a great repository. I was wondering, is it possible to use a `SparseTensor` as a parameter in a torch module? I am trying to figure out how to use these as parameters for a model.  An example of what I want to do can be seen below. 

```python3
import torch
import torch_sparse
class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        vecs = generate_vectors() # Generates a sparse matrix
        vecs_sp = torch_sparse.SparseTensor.from_torch_sparse_coo_tensor(vecs)
        self.param = torch.nn.Parameter(vecs, requires_grad=True) # This works
        self.param2 = torch.nn.Parameter(vecs_sp, requires_grad=True) # Of course raises an error
```

However, this of course this raises an error. 

```python3
>>> test = TestModule()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in __init__
  File "/home/filco306/.envs/kg-env/lib/python3.8/site-packages/torch/nn/parameter.py", line 26, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not SparseTensor
```

The reason I am looking to use yours is (not only that it is very nice of course) but because `select_index()` is extremely slow for sparse coo tensors in pytorch, while you have implemented a very nice and fast version. 

Thank you!

**Comment by rusty1s** [comment]
I think what you want to do is pass a `Parameter` to the `value` argument of a `SparseTensor`, which should work just fine:
```
self.vecs_sp = torch_sparse.SparseTensor.from_torch_sparse_coo_tensor(vecs)
_, _, value = self.vecs_sp.coo()
self.param = Parameter(value)
self.vecs_sp.set_value(self.param, layout='coo')
```

**Comment by Filco306** [comment]
Thank you for your reply! I will try this and return to you! I was wondering though; I want to do element-wise addition and subtraction of two vectors. Is this possible? I tried to do this, but it did not work.

**Comment by rusty1s** [comment]
Do you mean element-wise addition of two sparse matrices? This is currently not supported. However, you can do element-wise multiplication with a dense vector, e.g.:
```python
sparse_mat * dense_vec.view(-1, 1)
```
or
```python
sparse_mat * dense_vec.view(1, -1)
```

**Comment by Filco306** [comment]
Closing this issue. Thanks for the help! :D
