### ISSUE TITLE
Runtime dependencies are not (correctly) specified

### ISSUE THREAD

**Issue by sisp** [rusty1s/pytorch_sparse#157]
`torch-sparse` has a number of runtime dependencies, but only `scipy` (without a version specifier) is specified in `setup.py` via `install_requires`. This breaks dependency resolution and makes it hard to use `torch-sparse` in a properly set up project.

I've identified the following dependencies:
- `numpy`
- `scipy`
- `torch`
- `torch-scatter`
- `typing-extensions>=3.7.4; python_version < '3.8'` (because `Final` was [added to the `typing` package in Python v3.8](https://docs.python.org/3/library/typing.html#typing.Final) and [to `typing-extensions` in v3.7.4](https://github.com/python/typing/commit/c6c7dfdd4b999a2bbd46d120adeacc504d74e044))

You should also determine proper version specifiers for the other dependencies, so that a dependency resolver can correctly determine the versions of all packages to be installed.

**Comment by rusty1s** [comment]
Thanks for creating the issue. We sadly cannot add `torch` nor `torch-scatter` as a dependency, as `torch` needs to be installed in advance to make installation succeed, and `torch-scatter` is best installed from wheels.

As such, the newly provided `conda` installation procedure fixes those problems and is now the recommended way to install `torch-sparse`.

**Comment by sisp** [comment]
> [...] as `torch` needs to be installed in advance to make installation succeed [...]

If we could solve #156, then `torch` could be added as a dependency, right?

> [...] and `torch-scatter` is best installed from wheels.

So the problem is that `torch-scatter` is only published as a source distribution package on pypi.org, right? Is there any reason why you don't publish wheels there?

> As such, the newly provided `conda` installation procedure fixes those problems and is now the recommended way to install `torch-sparse`.

Conda is becoming a bit of an issue for users engaged in commercial activities (i.e. enterprises) because they've changed their [terms of service](https://www.anaconda.com/terms-of-service). I'd be nice to have a proper setup path using standard Python packages. :slightly_smiling_face:

**Comment by rusty1s** [comment]
I'm not a big fan of adding `torch` as dependency, as it is totally unclear which PyTorch version (CUDA, CPU) gets installed (the same holds true for `torch-scatter` as its version needs to align with the PyTorch/CUDA version. That's also the reason why we cannot simply push wheels to PyPi, as binaries depend both on PyTorch and CUDA version.

**Comment by sisp** [comment]
Ah, yes, I see. :thinking:
