### ISSUE TITLE
What is the difference between pytorch.coalesce and pytorch_sparse.coalesce function?

### ISSUE THREAD

**Issue by LitLeo** [rusty1s/pytorch_sparse#158]
There's  coalesce  function in PyTorch, https://pytorch.org/docs/stable/generated/torch.Tensor.coalesce.html#torch.Tensor.coalesce
What is the difference between pytorch.coalesce and pytorch_sparse.coalesce function?

**Comment by rusty1s** [comment]
The functionality is identical and the difference is solely in the input. The PyTorch function expects a `torch.(Sparse)Tensor`, while we expect two individual tensors (one for indices and one for values).
