### ISSUE TITLE
ImportError: libcusparse.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by veophi** [rusty1s/pytorch_sparse#16]
Hi, Thanks for your torch-geometric codes.
I have some problems that is really confused me.

GPU: TITAN RTX
CUDA: 10.0
PyTorch: 1.1.0

I followed the https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html to install torch-sparse, but the error was reported when I tried to run my code.

echo $PATH
/ENV/anaconda3/envs/TORCH1.1/bin:/usr/local/cuda/bin:/usr/local/cuda/bin:/ENV/anaconda3/bin:/home/titian/bin:/home/titian/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

echo $CPATH
/usr/local/cuda/include:/usr/local/cuda/include:

Thanks again!

**Comment by rusty1s** [comment]
Hi, can you follow [this guide](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html) and see if that fixes your issue?

**Comment by veophi** [comment]
This issue was solved ! 
It caused by my conda virtual env . 
I used /usr/lobal/cuda to compiler the torch-sparse . 
However , my codes depend on the virtual env when it runs . . .
So I just moved the libcusparse.so.10.0 files from /usr/lobal/cuda/lib64 to my virtual env , then it was solved!
Thanks so much !! !

**Comment by roholazandie** [comment]
I run into the same problem. My Cuda version is 10.0. Is there any way that I could install it with this version or should I upgrade?

**Comment by rusty1s** [comment]
If your CUDA version is 10.0 and you use PyTorch 1.5, you may need to install from source using `pip install torch-sparse` command. The easier way is to just upgrade your CUDA though.

**Comment by roholazandie** [comment]
> If your CUDA version is 10.0 and you use PyTorch 1.5, you may need to install from source using `pip install torch-sparse` command. We provide 9.2, 10.1 and 10.2 wheels for PyTorch 1.5, and 9.2, 10.0 and 10.1 wheels for PyTorch 1.4. The easier way is to just upgrade your CUDA though.

Yes, I upgraded my cuda version and that saved me a lot of time playing around with library versions

**Comment by bsaberla** [comment]
> This issue was solved !
> It caused by my conda virtual env .
> I used /usr/lobal/cuda to compiler the torch-sparse .
> However , my codes depend on the virtual env when it runs . . .
> So I just moved the libcusparse.so.10.0 files from /usr/lobal/cuda/lib64 to my virtual env , then it was solved!
> Thanks so much !! !

I am using virtual environment too. But there is not any cuda directory in local directory. my torch cuda version however is 10.1. How can I fix this?

**Comment by rusty1s** [comment]
You may need to add the `lib` directory of `miniconda` to `LD_LIBRARY_PATH`. This directory should contain `libcusparse.so.10`.

**Comment by mayurmallya** [comment]
Appending $CUDA_PATH/lib64 (which has libcusparse.so.10.0) to $LD_LIBRARY_PATH help me resolve this issue.

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_PATH/lib64`
