### ISSUE TITLE
How to obtain the edge_index of the SparseTensor?

### ISSUE THREAD

**Issue by mohit-raghavendra** [rusty1s/pytorch_sparse#161]
SparseTensor class has a from_edge_index() method to convert the edge_index to a SparseTensor. I couldn't find a to_edge_index method though. I wanted to know if there is a way to obtain the edge_index from a SparseTensor?

My use-case is that I the edge_index of a graph on the Open Graph Benchmark. The data.full_adj_t is a SparseTensor and I would want to get its edge_index. 

Thanks!

**Comment by TobiasSchmidtDE** [comment]
As far as I know there is no such function, but you can just as well write a two-liner to accomplish this:
```
adj = SparseTensor(....)
row, col, value = adj.coo()
index = torch.stack([row, col], dim=0)
```

In your case, you might also be able to leverage the fact that OGB datasets usually provide the edge indices as a property:

```
from ogb.nodeproppred import PygNodePropPredDataset
pyg_dataset = PygNodePropPredDataset(name="ogbn-arxiv")

edge_index = pyg_dataset[0].edge_index
edge_weights = pyg_dataset[0].edge_attr
```

**Comment by mohit-raghavendra** [comment]
Awesome, this was really helpful. 
Thank you!
