### ISSUE TITLE
torch sparsh 0.4.3 install error 

### ISSUE THREAD

**Issue by Rajkumarsaswamy** [rusty1s/pytorch_sparse#167]
Hi i have  installed

pytorch-lightning     0.5.2.1        
torch                 1.3.0          
torch-cluster         1.4.5          
torch-geometric       1.3.2          
torch-scatter         1.4.0          
torchvision           0.4.1a0+d94043a

But when i try to install torch sparse by
pip install --no-binary torch-sparse==0.4.3 torch-sparse==0.4.3 --no-cache-dir 

i get following error 

Collecting torch-sparse==0.4.3
  Downloading https://files.pythonhosted.org/packages/08/4e/a268613fa6a92ffbc65b89e66fc8be5590801937185007f0f7bcb75ea21f/torch_sparse-0.4.3.tar.gz
Requirement already satisfied: scipy in /home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages (from torch-sparse==0.4.3) (1.3.1)
Requirement already satisfied: numpy>=1.13.3 in /home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages (from scipy->torch-sparse==0.4.3) (1.17.2)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rajkumar/anaconda3/envs/bayesraj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qtqcey3l --python-tag cp37
       cwd: /tmp/pip-install-8cnf41rs/torch-sparse/
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/transpose.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/spmm.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/eye.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/convert.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/__init__.py -> build/lib.linux-x86_64-3.7/torch_sparse
  copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-3.7/torch_sparse
  creating build/lib.linux-x86_64-3.7/test
  copying test/test_eye.py -> build/lib.linux-x86_64-3.7/test
  copying test/utils.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_spmm.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_transpose.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_convert.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_coalesce.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_spspmm_spmm.py -> build/lib.linux-x86_64-3.7/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.7/test
  copying test/test_spspmm.py -> build/lib.linux-x86_64-3.7/test
  creating build/lib.linux-x86_64-3.7/torch_sparse/utils
  copying torch_sparse/utils/unique.py -> build/lib.linux-x86_64-3.7/torch_sparse/utils
  copying torch_sparse/utils/__init__.py -> build/lib.linux-x86_64-3.7/torch_sparse/utils
  running build_ext
  building 'torch_sparse.spspmm_cpu' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/cpu
  gcc -pthread -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cpu/spspmm.cpp -o build/temp.linux-x86_64-3.7/cpu/spspmm.o -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -L/home/rajkumar/anaconda3/envs/bayesraj/lib -Wl,-rpath=/home/rajkumar/anaconda3/envs/bayesraj/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu/spspmm.o -o build/lib.linux-x86_64-3.7/torch_sparse/spspmm_cpu.cpython-37m-x86_64-linux-gnu.so
  building 'torch_sparse.spspmm_cuda' extension
  creating build/temp.linux-x86_64-3.7/cuda
  gcc -pthread -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cuda/spspmm.cpp -o build/temp.linux-x86_64-3.7/cuda/spspmm.o -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /usr/local/cuda/bin/nvcc -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cuda/spspmm_kernel.cu -o build/temp.linux-x86_64-3.7/cuda/spspmm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
  /home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

  cuda/spspmm_kernel.cu(76): error: identifier "cusparseXcsrgemmNnz" is undefined

  cuda/spspmm_kernel.cu(84): error: identifier "cusparseScsrgemm" is undefined

  cuda/spspmm_kernel.cu(84): error: identifier "cusparseDcsrgemm" is undefined

  3 errors detected in the compilation of "cuda/spspmm_kernel.cu".
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-sparse
  Running setup.py clean for torch-sparse
Failed to build torch-sparse
Installing collected packages: torch-sparse
    Running setup.py install for torch-sparse ... error
    ERROR: Command errored out with exit status 1:
     command: /home/rajkumar/anaconda3/envs/bayesraj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-87wwtjm5/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-8cnf41rs/torch-sparse/
    Complete output (48 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/transpose.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/spmm.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/eye.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/convert.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/__init__.py -> build/lib.linux-x86_64-3.7/torch_sparse
    copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-3.7/torch_sparse
    creating build/lib.linux-x86_64-3.7/test
    copying test/test_eye.py -> build/lib.linux-x86_64-3.7/test
    copying test/utils.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_spmm.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_transpose.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_convert.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_coalesce.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_spspmm_spmm.py -> build/lib.linux-x86_64-3.7/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_spspmm.py -> build/lib.linux-x86_64-3.7/test
    creating build/lib.linux-x86_64-3.7/torch_sparse/utils
    copying torch_sparse/utils/unique.py -> build/lib.linux-x86_64-3.7/torch_sparse/utils
    copying torch_sparse/utils/__init__.py -> build/lib.linux-x86_64-3.7/torch_sparse/utils
    running build_ext
    building 'torch_sparse.spspmm_cpu' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cpu
    gcc -pthread -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cpu/spspmm.cpp -o build/temp.linux-x86_64-3.7/cpu/spspmm.o -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -L/home/rajkumar/anaconda3/envs/bayesraj/lib -Wl,-rpath=/home/rajkumar/anaconda3/envs/bayesraj/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu/spspmm.o -o build/lib.linux-x86_64-3.7/torch_sparse/spspmm_cpu.cpython-37m-x86_64-linux-gnu.so
    building 'torch_sparse.spspmm_cuda' extension
    creating build/temp.linux-x86_64-3.7/cuda
    gcc -pthread -B /home/rajkumar/anaconda3/envs/bayesraj/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cuda/spspmm.cpp -o build/temp.linux-x86_64-3.7/cuda/spspmm.o -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda/bin/nvcc -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/TH -I/home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/rajkumar/anaconda3/envs/bayesraj/include/python3.7m -c cuda/spspmm_kernel.cu -o build/temp.linux-x86_64-3.7/cuda/spspmm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
    /home/rajkumar/anaconda3/envs/bayesraj/lib/python3.7/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

    cuda/spspmm_kernel.cu(76): error: identifier "cusparseXcsrgemmNnz" is undefined

    cuda/spspmm_kernel.cu(84): error: identifier "cusparseScsrgemm" is undefined

    cuda/spspmm_kernel.cu(84): error: identifier "cusparseDcsrgemm" is undefined

    3 errors detected in the compilation of "cuda/spspmm_kernel.cu".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rajkumar/anaconda3/envs/bayesraj/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8cnf41rs/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-87wwtjm5/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rusty1s** [comment]
Which CUDA version are you using?

**Comment by Rajkumarsaswamy** [comment]
10.1

**Comment by Rajkumarsaswamy** [comment]
Hi, could you please help me?

**Comment by rusty1s** [comment]
Are you sure you are installing with CUDA 10.1 as the `cusparseXcsrgemmNnz` routine was removed in CUDA 11.0. What's the output of `nvcc --version`?

**Comment by Rajkumarsaswamy** [comment]
Am actually in WSL2. nvcc - - version isn't working!

**Comment by rusty1s** [comment]
What do you mean with it's not working? Since you have `nvcc` installed, writing `nvcc --version` should give you an output :)

**Comment by Rajkumarsaswamy** [comment]
Sorry for confusion. The output is 10.1.168

**Comment by rusty1s** [comment]
Thanks. This is a bit weird :) Do there exists multiple CUDA versions on your machine?

**Comment by Rajkumarsaswamy** [comment]
Yes that's True!

**Comment by GU1QUAN** [comment]
hey,how do you solve it ,i have the same problem.
cuda/spspmm_kernel.cu(76): error: identifier "cusparseXcsrgemmNnz" is undefined

cuda/spspmm_kernel.cu(84): error: identifier "cusparseScsrgemm" is undefined

cuda/spspmm_kernel.cu(84): error: identifier "cusparseDcsrgemm" is undefined

3 errors detected in the compilation of "cuda/spspmm_kernel.cu".
error: command '/usr/local/cuda-11.7/bin/nvcc' failed with exit code 1
my cuda version is 11.7
