### ISSUE TITLE
Make `SparseTensor` visible to `torch.nn.Module`

### ISSUE THREAD

**Issue by bwdeng20** [rusty1s/pytorch_sparse#168]
``` python3

import torch
import torch.nn as nn
from torch_sparse import SparseTensor

class Model(nn.Module):
    def __init__(self,spa,n):
        super(Model, self).__init__()
        self.spa=spa
        self.w=nn.Parameter(torch.rand(n,n))

a=torch.rand(4,4)
spa=SparseTensor.from_dense(a)
model=Model(spa,3)
model_on_gpu=model.cuda()
print(model_on_gpu.spa.device())
print(model_on_gpu.w.device)
# cpu
# cuda:0

```

We would expect the `model.spa` is sent to GPU by `model.cuda()`.  Is there any good way to achieve this? 
One workaround may be registering  items from `spa.coo()` as `nn.Parameter` as they are all `torch.Tensor`, but it seems not that concise.

**Comment by rusty1s** [comment]
Thanks for reporting. Note that this is intended, as it also fails for any vanilla PyTorch tensor. During the `model.to(device)` call, only parameters and buffers will be moved to the respective device. Registering bufers can be done via `self.register_buffer('spa', spa)`.

However, this will fail for `SparseTensor` as `register_buffer` only allows `torch.Tensor` as input. This is a current limitation. As an alternative, you can put `spa` into the buffer dictionary directly, i.e.:
```python
class Model(nn.Module):
    def __init__(self, spa, n):
        super(Model, self).__init__()
        self._buffers['spa'] = spa
        self.w = nn.Parameter(torch.rand(n, n))
```

**Comment by bwdeng20** [comment]
Thanks for your explanation. That's what I want indeed.
