### ISSUE TITLE
the version problem

### ISSUE THREAD

**Issue by lbq8942** [rusty1s/pytorch_sparse#170]
it's so annoying that sparse require torch1.8,instead i am 1.9 because of  a another package requires

**Comment by rusty1s** [comment]
I'm not sure what you mean. `torch-sparse` works for both PyTorch 1.8 and PyTorch 1.9.

**Comment by lbq8942** [comment]
![image](https://user-images.githubusercontent.com/64315774/132649254-8c40f723-1ca4-4d3d-8bd6-7b519cd557a3.png)

**Comment by rusty1s** [comment]
You need to install via `conda install pytorch-sparse -c rusty1s`. I'm not the maintainer of the `esri` channel.

**Comment by lbq8942** [comment]
may be i am wrong using "-c esri"?

**Comment by lbq8942** [comment]
oh,i am sorry

**Comment by lbq8942** [comment]
thank you so much
