### ISSUE TITLE
Is there any difference between torch_geometric.utils.subgraph and SparseTensor.saint_subgraph?

### ISSUE THREAD

**Issue by Guangxuan-Xiao** [rusty1s/pytorch_sparse#171]
Their functions seem the same to me. Is there any performance or other difference between these methods?

**Comment by rusty1s** [comment]
The difference is that `utils.subgraph` works on the `edge_index` representation, while the version in `torch-sparse´ operates on the `SparseTensor` representation and should be slightly faster as a result. Other-wise, the outputs of both functions should be identical.

**Comment by Guangxuan-Xiao** [comment]
Thanks!
