### ISSUE TITLE
Doesn't build on aarch64

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [rusty1s/pytorch_sparse#173]
ERROR: CppTypeToScalarType is not a member c
10

**Comment by rusty1s** [comment]
Can you give some more information about your PyTorch version/OS?

**Comment by AlexandrParkhomenko** [comment]
OS is Android 64 bit. PyTorch 1.5.0

**Comment by rusty1s** [comment]
Can you try to install version `0.6.7`? This is the latest supported version for PyTorch 1.5.0, see [here](https://pytorch-geometric.com/whl/torch-1.5.0%2Bcpu.html).

**Comment by AlexandrParkhomenko** [comment]
All is OK. Thank you.
