### ISSUE TITLE
A new issue got introduced during the last storage.py change

### ISSUE THREAD

**Issue by LumRamabaja** [rusty1s/pytorch_sparse#181]
I'm not sure what exactly is causing the error, but this code snippet worked in previous versions:

```python
from torch_sparse import coalesce

U = torch.tensor([0,1,0,2,1,3,4,6]) 
V = torch.tensor([0,0,0,0,2,4,3,5])

new_e = sort(cat((U.unsqueeze(0),V.unsqueeze(0)), dim=0), dim=0).values

m = unique(new_e[0,:]).size(0)
n = unique(new_e[1,:]).size(0)

values = torch.Tensor([1,1,1,1,1,1,1,1])

coalesce(new_e, values, m=m, n=n, op = 'mean')
```

Any idea why coalesce does not accept anymore scenarios like this one?

**Comment by LumRamabaja** [comment]
Hmm, ok, so apparently if m and n are set to the number of nodes in the graph (7 in this case), it works

**Comment by rusty1s** [comment]
Your shape (`m` and `n`) needs to be defined as the maximum value in `U` and `V` + 1, respectively:
```python
m = int(new_e[0].max()) + 1
n = int(new_e[1].max()) + 1
```

**Comment by LumRamabaja** [comment]
Ah, makes sense. Thanks for the feedback (and great work with the package)!
