### ISSUE TITLE
the matched version of pytorch_sparse, pytorch_scatter, pytorch_geometric & pytorch_cluster

### ISSUE THREAD

**Issue by wwddd66** [rusty1s/pytorch_sparse#184]
could u tell me what the matched version of pytorch_sparse, pytorch_scatter, pytorch_geometric & pytorch_cluster should be? Thank you very much!

**Comment by rusty1s** [comment]
For which PyG/PyTorch version?

**Comment by wwddd66** [comment]
torch 1.4.0

**Comment by rusty1s** [comment]
You can see all supported versions [here](https://data.pyg.org/whl/torch-1.4.0%2Bcpu.html):
```
torch-cluster==1.5.4
torch-scatter==2.0.4
torch-sparse==0.6.1
torch-spline-conv==1.2.0
```
For PyG, you may try `torch--geometric==1.6.1`. If that doesn't work, use `torch-geometric==1.5.0`.

**Comment by wwddd66** [comment]
Excuse me, if i change the torch version, How to know the matched version of these? May I know the manner about selecting matched version?

**Comment by rusty1s** [comment]
You can look at https://data.pyg.org/whl/index.html, select your PyTorch versions and look at the latest supported versions.
