### ISSUE TITLE
batch sparse - dense multiplication

### ISSUE THREAD

**Issue by pralaydas** [rusty1s/pytorch_sparse#185]
How we can multiply batch sparse dense multiplication? I see here this approach is valid only for 2-dimensional data, because in graph data most of the adjacency matrix is sparse and we need to multiply with sparse with dense matrix.

**Comment by rusty1s** [comment]
You mean 3-dimensional sparse tensors? This is usually done by stacking sparse matrices diagonally, and the dense matrix in the first dimension:
```python
from torch_sparse import cat

sparse_mats = [...]  # List of SparseTensors
dense_mats = [...]  # List of dense matrices

sparse_mat = cat(sparse_mats, dim=(0, 1))
dense_mat = torch.cat(dense_mats, dim=0)

out = sparse_mat @ dense_mat
```

**Comment by pralaydas** [comment]
1. In which module we need to install to run torch_sparse?
2. suppose we have tensors of 3 dimensions not list of tensors, the what we do? if we change to list of tensors, it is time consuming, So is there any approach to beat(time or space) torch.matmul for sparse-dense tensor multiplication for multi dimensional tensors.

**Comment by rusty1s** [comment]
Note that this will not process sparse tensors as a list of tensors, it will stack them diagonally. Ideally, this should be done in a pre-processing step.
