### ISSUE TITLE
input_indices in `neighbor_sample`

### ISSUE THREAD

**Issue by Lintianqianjin** [rusty1s/pytorch_sparse#187]
Hi, could you please explain how to identify the `input_indices` in the returned data object after calling neighbor_sample?

**Comment by rusty1s** [comment]
`neighbor_sample` does return 4 tensors:
1. the node indices that groups the input nodes and all sampled nodes
2. The `row` vector of the resulting sparse adjacency matrix `edge_index`
3. The `col` vector of the resulting sparse adjacency matrix `edge_index`
4. The edge indices of all edges involved in sampling

The `input_indices` in the returned data are placed first in the output node indices, such that:
```python
output_indices, _, _, _ = neighbor_sample(..., input_indices, ...)
assert output_indices[:input_indices.numel()].tolist() == input_indices.tolist()
