### ISSUE TITLE
Different CUDA versions than PyTorch

### ISSUE THREAD

**Issue by samahwaleed** [rusty1s/pytorch_sparse#189]
I'm trying to run PyTorch Geometric, and I installed all needed libraries using:
```
!pip3 install torch-scatter
!pip3 install torch-sparse
!pip3 install torch-cluster
!pip3 install torch-spline-conv
!pip3 install torch-geometric
```

but I got this error:
 ```
RuntimeError:
    The detected CUDA version (11.2) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.
```

**Comment by rusty1s** [comment]
Yes, I think you have a local CUDA 11.2 installed on your machine, while you are using PyTorch compiled for 10.2. You should install the PyTorch that matches with your local CUDA installation, *e.g.*, PyTorch with CUDA 11.*.
