### ISSUE TITLE
Problem encountered when import torch_sparse 

### ISSUE THREAD

**Issue by esflfei** [rusty1s/pytorch_sparse#190]
I encountered the following problem when import torch_sparse:
`>>> import torch_sparse`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/usr/local/lib/python3.6/dist-packages/torch_sparse/__init__.py", line 15, in <module>`
    `f'{library}_{suffix}', [osp.dirname(__file__)]).origin)`
`AttributeError: 'NoneType' object has no attribute 'origin'`

Here are some of my package versions:
python==3.6.9
torch==1.9.0+cu102
torch-geometric==1.6.3
torch-scatter==2.0.8
torch-sparse== 0.6.11
torchvision==0.10.0

Can you help me?

**Comment by rusty1s** [comment]
This usually indicates that installation of C++/CUDA extensions failed. Please let me know how you tried to install `torch_sparse` and any installation logs.
