### ISSUE TITLE
Consider exporting symbols in the DLL

### ISSUE THREAD

**Issue by dfalbel** [rusty1s/pytorch_sparse#197]
Unlike unix, on Windows only symbols declared as exported can be used from a DLL. There are a few ways of declaring exported symbols eg:

- using a [module definition file](https://docs.microsoft.com/en-us/cpp/build/reference/module-definition-dot-def-files?view=msvc-170&viewFallbackFrom=vs-2017) 
- setting [`WINDOWS_EXPORT_ALL_SYMBOLS`](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) in CMake

But it looks like the most widespread way of declaring is to add a macro like `SPARSE_API` and annotate exported functions with it. For example, [this](https://github.com/pytorch/vision/blob/7947fc8fb38b1d3a2aca03f22a2e6a3caa63f2a0/torchvision/csrc/macros.h#L3-L11 ) is what PyTorch Vision project uses:

```
#ifdef _WIN32
#if defined(torchvision_EXPORTS)
#define VISION_API __declspec(dllexport)
#else
#define VISION_API __declspec(dllimport)
#endif
#else
#define VISION_API
#endif
```

Would you consider a PR adding this annotations to functions in the public API, ie. functions  declared in the `sparse.h` header?

See also [this](https://stackoverflow.com/a/32284832/3297472) SO post with more detail on symbol exporting.

**Comment by rusty1s** [comment]
I'm definitely supportive of adding better Windows support to this library. Please feel free to go ahead :)
