### ISSUE TITLE
Apple silicon (m1 Mac) compatibility 

### ISSUE THREAD

**Issue by amitt1236** [rusty1s/pytorch_sparse#199]
All of the following packages has the same issue:
pytorch_sparse
pytorch_scatter
pytorch_cluster
pytorch_spline_conv

They install fine on M1 Mac but you can't import them because they compiled to x86_64
Even when I tried building from source, I encountered the same problem.

```
OSError: dlopen(/opt/homebrew/lib/python3.9/site-packages/torch_spline_conv/_version_cpu.so, 0x0006): tried:  

'/opt/homebrew/lib/python3.9/site-packages/torch_spline_conv/_version_cpu.so' (mach-o file, but is an incompatible   

architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_version_cpu.so' (no such file), '/usr/lib/_version_cpu.so' (no   

such file)
```

To solve it I had to uninstall all the packages, and then install them from source using `arch -arm64` flag 
forcing the terminal not to compile under rosseta.

`
arch -arm64 python3 setup.py install
`

Are you intending to support apple silicon?
maybe I can help with building a whl for m1 Mac?

**Comment by rusty1s** [comment]
I'm definitely interested in supporting M1 chips. I sadly don't have access to one yet, so I currently need to rely community support for this. We might need to add something to [`setup.py`](https://github.com/rusty1s/pytorch_sparse/blob/master/setup.py) which adds the necessary flags whenever it detects an ARM-based architecture.

**Comment by pythonpanda2** [comment]
I tried `arch -arm64 python3 setup.py install`


Unfortunately it is still running in to 

```
File ~/miniconda3/envs/M1Max/lib/python3.8/site-packages/torch_geometric/typing.py:4, in <module>
      1 from typing import Tuple, Optional, Union, List
      3 from torch import Tensor
----> 4 from torch_sparse import SparseTensor

OSError: dlopen(/Users/gsivaraman/miniconda3/envs/M1Max/lib/python3.8/site-packages/torch_sparse/_convert_cpu.so, 0x0006): Symbol not found: __ZN2at5emptyEN3c108ArrayRefIxEENS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE
  Referenced from: /Users/gsivaraman/miniconda3/envs/M1Max/lib/python3.8/site-packages/torch_sparse/_convert_cpu.so
  Expected in: /Users/gsivaraman/miniconda3/envs/M1Max/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
```

**Comment by amitt1236** [comment]
> 

It doesn't look like m1 problem, I think the problem is with the Miniconda environment.
and you don't need to  ```arch -arm64 python3 setup.py install``` as the ```arch -arm64``` flag is now implemented into 
the ```setup.py```  file, so ```python3 setup.py install``` should be enough.

I don't use conda so I can't offer much help, maybe someone else ?

**Comment by pythonpanda2** [comment]
Very interesting.I switched from an Intel to M1 Max Mac.  It seems Miniconda is the recommended way to get started. I tried many combinations  and it almost always leads to this same error. Thanks for the suggestion. I will keep trying.

**Comment by pythonpanda2** [comment]
Found a [fix](https://github.com/rusty1s/pytorch_scatter/issues/241)
