### ISSUE TITLE
py310 support

### ISSUE THREAD

**Issue by konstantinosKokos** [rusty1s/pytorch_sparse#201]
when should we anticipate python 3.10 support?

**Comment by rusty1s** [comment]
I will release a new version once PyTorch 1.11 lands (I think in a few weeks), and will integrate Python 3.10 support to it.

**Comment by konstantinosKokos** [comment]
thanks a bunch for the quick answer, looking forward to the new version :)

**Comment by rusty1s** [comment]
This has been integrated long ago :)
