### ISSUE TITLE
Neighbor Sampling: rand() <-> uniform distribution

### ISSUE THREAD

**Issue by ZenoTan** [rusty1s/pytorch_sparse#216]
In [neighbor sampling](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/sample_cpu.cpp#L72):
The use of `rand()` is not appropriate for a real uniform distribution. Instead, we could try sth from STL random to generate it.

Reference: see the answer in [StackOverflow](https://stackoverflow.com/questions/288739/generate-random-numbers-uniformly-over-an-entire-range)

**Comment by rusty1s** [comment]
Thanks for reporting @ZenoTan. We could either try random number generation from STL or from PyTorch directly. The latter may be preferred due to respecting `torch.manual_seed`.
