### ISSUE TITLE
`test_ind2ptr` fails after `torch.Tensor.tolist` was updated to error out when called on tensors with null storage

### ISSUE THREAD

**Issue by anjali411** [rusty1s/pytorch_sparse#221]
Looks like https://github.com/rusty1s/pytorch_sparse/blob/eabdc5846a2080db87d5d5955773f41dec8d6c7a/test/test_storage.py#L23-L24 started failing after https://github.com/pytorch/pytorch/pull/75990 landed
```
        row = torch.ops.torch_sparse.ptr2ind(rowptr, 0)
>       assert row.tolist() == []
E       RuntimeError: tolist() shouldn't be called on a tensor with unallocated storage
```

**Comment by rusty1s** [comment]
Thanks for sharing. Do you have any pointers on how to fix this on our end?

**Comment by anjali411** [comment]
@rusty1s Hey so unfortunately `torch.empty(0)` in python is not the same as `torch::empty(0)` in C++. I think changing https://github.com/rusty1s/pytorch_sparse/blob/7a6c9ab4d003bf30b98fb7435e4b8509a82771fe/csrc/cpu/convert_cpu.cpp#L39 to `auto out = torch::empty({E}, ptr.options());` should fix it

**Comment by rusty1s** [comment]
Thank you for digging into this. Can you send a PR?

**Comment by anjali411** [comment]
I don't think I will get to it until next week. It would be nice if this is fixed asap so that the PR doesn't get reverted

**Comment by rusty1s** [comment]
Fixed this via https://github.com/rusty1s/pytorch_sparse/pull/222. Thank you!
