### ISSUE TITLE
Algorithm about SpMM

### ISSUE THREAD

**Issue by shi27feng** [rusty1s/pytorch_sparse#229]
Hi @rusty1s,
Sorry that this is not a real issue post.
Recently, I'm reading the [spmm cuda code](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cuda/spmm_cuda.cu), and I'm wondering which part of the code implementing the function **_PartitionSpmm_** mentioned in the paper "Design principles for SpMM on the GPU"?

Thanks in advance

**Comment by rusty1s** [comment]
Thanks for your interest. For our SpMM implementation, we only implement the row-splitting algorithm.

**Comment by shi27feng** [comment]
Thank you very much for the reply!
