### ISSUE TITLE
Citing package?

### ISSUE THREAD

**Issue by anandtrex** [rusty1s/pytorch_sparse#230]
Please add a way to cite the package, so that a person can quickly see which papers use this package. 
AFAIK Github provides a built-in feature to enable citations by just adding a CITATION.cff file: https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
Thanks!

**Comment by rusty1s** [comment]
Please cite [PyTorch Geometric](https://github.com/pyg-team/pytorch_geometric#cite) when using this package.

**Comment by anandtrex** [comment]
Might want to put that up on the readme file too.
