### ISSUE TITLE
Seed, reproducibility 

### ISSUE THREAD

**Issue by agosztolai** [rusty1s/pytorch_sparse#232]
Hello, 

Is there a way to make the output of `torch.ops.torch_sparse.sample_adj` deterministic in torch_sparse.sample.py? I would like to get the same samples every time I run the code.

`torch.manual_seed(0)` does not work

Thanks!

**Comment by rusty1s** [comment]
We just added support for this in master. You can either install from master or wait for the next release.

**Comment by rusty1s** [comment]
Indeed. Thanks!
