### ISSUE TITLE
Can't import torch_sparse after running setup.py

### ISSUE THREAD

**Issue by berkekisin** [rusty1s/pytorch_sparse#233]
Hi Matthias,
I wanted to test "spmm_coo", so I ran "python setup.py install". It compiled without errors but as I tried to import torch_sparse I received the following error:
![Screenshot from 2022-05-24 14-28-37](https://user-images.githubusercontent.com/70319815/170034732-cb368d09-871f-413f-8c1d-b9064e4f4ef9.png)
I also tried to run setup.py and import torch_sparse without spmm_coo and I received the same error.

**Comment by rusty1s** [comment]
Can you show me the installation log of running
```
rm -rf build/
python setup.py clean
python setup.py develop
```

**Comment by berkekisin** [comment]
hello Matthias this worked thanks. I am ready to create PR but the current implementation does not support values in sparse tensor, should I create the pr first once I added it or can I add it later? And you said, "Provide general interface + documentation". Do you mean a  "spmm_coo.py" file in directory torch_sparse and documentation there?

**Comment by rusty1s** [comment]
Hi @berkekisin. Yes, this is what I meant. We can set up a similar file structure as for our CSR-based `spmm` operation:
* https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/spmm.cpp
* https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/matmul.py

**Comment by SauravMaheshkar** [comment]
I assume the purpose of this issue is resolved ? CC: @rusty1s

**Comment by rusty1s** [comment]
Yes, related PR: https://github.com/rusty1s/pytorch_sparse/pull/237
