### ISSUE TITLE
install without GPU

### ISSUE THREAD

**Issue by meltzerpete** [rusty1s/pytorch_sparse#24]
Is it possible to install for use only with CPU?
I get the following error on installation:

```
$ pip install torch-sparse
Collecting torch-sparse
  Using cached https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz
Requirement already satisfied: scipy in /home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages (from torch-sparse) (1.3.0)
Requirement already satisfied: numpy>=1.13.3 in /home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages (from scipy->torch-sparse) (1.16.4)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... error
  ERROR: Complete output from command /home/pete/miniconda3/envs/pinet2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-mizghsjn/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v_tqug6l --python-tag cp36:
  ERROR: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/eye.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/spmm.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/convert.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/__init__.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/transpose.py -> build/lib.linux-x86_64-3.6/torch_sparse
  copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-3.6/torch_sparse
  creating build/lib.linux-x86_64-3.6/test
  copying test/utils.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_eye.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_spspmm_spmm.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_spspmm.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_convert.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_coalesce.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_transpose.py -> build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_spmm.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/torch_sparse/utils
  copying torch_sparse/utils/unique.py -> build/lib.linux-x86_64-3.6/torch_sparse/utils
  copying torch_sparse/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_sparse/utils
  running build_ext
  building 'torch_sparse.spspmm_cpu' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cpu
  gcc -pthread -B /home/pete/miniconda3/envs/pinet2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/TH -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/THC -I/home/pete/miniconda3/envs/pinet2/include/python3.6m -c cpu/spspmm.cpp -o build/temp.linux-x86_64-3.6/cpu/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/pete/miniconda3/envs/pinet2/compiler_compat -L/home/pete/miniconda3/envs/pinet2/lib -Wl,-rpath=/home/pete/miniconda3/envs/pinet2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/spspmm.o -o build/lib.linux-x86_64-3.6/torch_sparse/spspmm_cpu.cpython-36m-x86_64-linux-gnu.so
  building 'torch_sparse.spspmm_cuda' extension
  creating build/temp.linux-x86_64-3.6/cuda
  gcc -pthread -B /home/pete/miniconda3/envs/pinet2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/TH -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/pete/miniconda3/envs/pinet2/include/python3.6m -c cuda/spspmm.cpp -o build/temp.linux-x86_64-3.6/cuda/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /usr/local/cuda/bin/nvcc -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/TH -I/home/pete/miniconda3/envs/pinet2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/pete/miniconda3/envs/pinet2/include/python3.6m -c cuda/spspmm_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/spspmm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  unable to execute '/usr/local/cuda/bin/nvcc': No such file or directory
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-sparse
  Running setup.py clean for torch-sparse
Failed to build torch-sparse
```

I have already install pytorch:

```
$ python -c "import torch; print(torch.__version__)" 
1.1.0
```

I don't have CUDA since I don't have a GPU, but the readme states that "All included operations work on varying data types and are implemented both for CPU and GPU." So how can I use this only with CPU?

I also get the same error for torch-scatter.

Any help appreciated.

**Comment by rusty1s** [comment]
We use [this method](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L25) to determine whether to install both for CPU and GPU. GPU installation is skipped if the method returns `None`. In your case, that means that `/usr/local/cuda` exists. Hence, PyTorch thinks you have CUDA installed.

**Comment by meltzerpete** [comment]
Thanks for the fast response!

It turns out CUDA is installed on this system, but the graphics card is turned off. I've managed to install for CPU by installing from source and removing the lines from `setup.py` that check for CUDA and install the CUDA extensions. This also worked for torch-scatter. Had a bit of trouble getting torch-cluster to install in the same way, I even tried hacking the `cpp_extension.py#_find_cuda_home()` method you indicated to return `None` but I then ran in to a different issue. I've finally got it working by building from commit https://github.com/rusty1s/pytorch_cluster/commit/f7e9e8fdbdcf60ba9eb6cea17266d3549beea86d and removing the lines in `setup.py` as mentioned above.

It would be awesome if there was a way to specify CPU only as an option to prevent calling the method to look for CUDA etc., but I appreciate your great work on this. Thanks!

**Comment by rusty1s** [comment]
Yes, `torch-cluster` is updated to work with `torch-nightly` on master. Good detective work :) I think we could add an argument to the `setup.py` command to make this process more straightforward.

**Comment by rosanajurdi** [comment]
Hello, 

I dont have cuda on my system. I was wondering if I could install torch_sparse without it?
THank you,

**Comment by rosanajurdi** [comment]
udo, you may want sudo's -H flag.
Collecting torch-sparse
  Downloading https://files.pythonhosted.org/packages/0e/bf/6242893c898621e7e4756e1ad298e903df6dfae208aec1c32adf8cfd1f7f/torch_sparse-0.4.4.tar.gz
Collecting scipy (from torch-sparse)
  Downloading https://files.pythonhosted.org/packages/24/40/11b12af7f322c1e20446c037c47344d89bab4922b8859419d82cf56d796d/scipy-1.2.3-cp27-cp27mu-manylinux1_x86_64.whl (24.8MB)
    100% |████████████████████████████████| 24.8MB 66kB/s 
Collecting numpy>=1.8.2 (from scipy->torch-sparse)
  Downloading https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 96kB/s 
Installing collected packages: numpy, scipy, torch-sparse
  Found existing installation: numpy 1.11.1
    Uninstalling numpy-1.11.1:
      Successfully uninstalled numpy-1.11.1
  Found existing installation: scipy 0.18.0
    Uninstalling scipy-0.18.0:
      Successfully uninstalled scipy-0.18.0
  Running setup.py install for torch-sparse ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-W57iGd/torch-sparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RSEF0V-record/install-record.txt --single-version-externally-managed --compile:
    No CUDA runtime is found, using CUDA_HOME='/usr'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/test
    copying test/test_spspmm.py -> build/lib.linux-x86_64-2.7/test
    copying test/utils.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_convert.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_spmm.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_coalesce.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_spspmm_spmm.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_transpose.py -> build/lib.linux-x86_64-2.7/test
    copying test/test_eye.py -> build/lib.linux-x86_64-2.7/test
    copying test/__init__.py -> build/lib.linux-x86_64-2.7/test
    creating build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/transpose.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/spmm.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/convert.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/eye.py -> build/lib.linux-x86_64-2.7/torch_sparse
    copying torch_sparse/__init__.py -> build/lib.linux-x86_64-2.7/torch_sparse
    creating build/lib.linux-x86_64-2.7/torch_sparse/utils
    copying torch_sparse/utils/unique.py -> build/lib.linux-x86_64-2.7/torch_sparse/utils
    copying torch_sparse/utils/__init__.py -> build/lib.linux-x86_64-2.7/torch_sparse/utils
    running build_ext
    building 'torch_sparse.spspmm_cpu' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/cpu
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-UKCoZ3/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include -I/home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/TH -I/home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/THC -I/usr/include/python2.7 -c cpu/spspmm.cpp -o build/temp.linux-x86_64-2.7/cpu/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    In file included from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/ATen/ATen.h:9:0,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data.h:3,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h:4,
                     from /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/torch/extension.h:4,
                     from cpu/spspmm.cpp:1:
    cpu/spspmm.cpp: In lambda function:
    cpu/spspmm.cpp:36:48: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
       AT_DISPATCH_FLOATING_TYPES(valueA.scalar_type(), "spspmm_bw", [&] {
                                  ~~~~~~~~~~~~~~~~~~^~
    /home/eljurros/.local/lib/python2.7/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by rusty1s** [comment]
That's not a CUDA issue. It seems like you are using on older PyTorch version than we support.
