### ISSUE TITLE
Won't install when running "conda install pytorch-sparse -c pyg"

### ISSUE THREAD

**Issue by J-Himes** [rusty1s/pytorch_sparse#240]
Hello,
I'm receiving this message when trying to use conda install. I receive a similar message when trying to install torch-scatter and torch-cluster as well.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch-sparse -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.5,<3.6.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

And if I use "pip uninstall torch-sparse" after running the install, I get this message here, which I assume is confirming it wasn't installed:
WARNING: Skipping torch-sparse as it is not installed.

When running nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

And my PyTorch version is 1.10.2

Is there a fix for this, is this issue caused by my Python or Cuda version? Appreciate any help at all, thank you so much.

**Comment by berkekisin** [comment]
I think you should use Python 3.7 or higher.

**Comment by J-Himes** [comment]
> I think you should use Python 3.7 or higher.

Thank you, I was able to get it to work with a pip install instead. Appreciate it.
