### ISSUE TITLE
Einsum?

### ISSUE THREAD

**Issue by justanhduc** [rusty1s/pytorch_sparse#248]
Hey @rusty1s. Thanks for maintaining this great library. I am wondering if it is possible to support einsum for sparse matrix and tensor multiplication. Is there any difficulty? Thanks in advance!

**Comment by rusty1s** [comment]
We do not have any plans to integrate `einsum` support into `torch-sparse`. Which operation do you try to perform? Eventually, you might be able to do so with the tools already provided in `torch-sparse`.

**Comment by rusty1s** [comment]
This should be already supported in `torch-sparse`:
```python
from torch_sparse import SparseTensor
sparse_mat = SparseTensor(row=row, col=col, sparse_sizes(m, n))
dense_mat = torch.randn(b, n, d)
out = sparse_mat @ dense_mat  # b x m x d
```

**Comment by justanhduc** [comment]
Ok I missed it. Perhaps you may want to make it more visible in the readme. Anw thanks a lot!

**Comment by yonatansverdlov** [comment]
> This should be already supported in `torch-sparse`:
> 
> ```python
> from torch_sparse import SparseTensor
> sparse_mat = SparseTensor(row=row, col=col, sparse_sizes(m, n))
> dense_mat = torch.randn(b, n, d)
> out = sparse_mat @ dense_mat  # b x m x d
> ```

If I have a tensor ten1 of shape [b,n,dim,i] which is sparse, and tne2 tensor of shape [i,m] and I want to output ten1@ten2, how can I use what you did here?

**Comment by rusty1s** [comment]
This wouldn't be supported since sparse matrix multiplication cannot handle 4-dimensional tensors (needs to be 2 dimensions). Your best option is to reshape `ten1` into `[b * n * dim, i]`.

**Comment by yonatansverdlov** [comment]
Why not?
Will it be supported in the future?
Do you know something that helps with sparse tensor multiplication?

**Comment by rusty1s** [comment]
Likely not, `SparseTensor` is designed to have at most two sparse dimensions (while any other dimension afterwards can be dense).

**Comment by thomasahle** [comment]
+1 to einsum for sparse tensors. Or at least tensordot.
Since SparseTensor doesn't support reshape and view, it's quite hard to implement it manually.
