### ISSUE TITLE
OOM for spmm but not matrix.mm

### ISSUE THREAD

**Issue by justanhduc** [rusty1s/pytorch_sparse#249]
Hi @rusty1s. Thanks for making this repo. I tried to replace Pytorch `mm` by `spmm` in my project but I got OOM. Is it already well-known or should the memory usage be similar somewhat?

**Comment by rusty1s** [comment]
You can try to use `SparseTensor` instead:
```python
from torch_sparse import SparseTensor
sparse_mat = SparseTensor(row=..., col=..., value=..., size=(N, N))
out = sparse_mat @ dense_mat
```

**Comment by justanhduc** [comment]
Great it works! Thanks!
