### ISSUE TITLE
torch_sparse document

### ISSUE THREAD

**Issue by downeykking** [rusty1s/pytorch_sparse#258]
Thanks for maintaining this great library. I am wondering if there has any document of torch_sparse? Thanks in advance!

**Comment by rusty1s** [comment]
Not really, sorry. There only exists some brief documentation here: https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html
Otherwise, you currently have to browse the source code.

**Comment by downeykking** [comment]
> Not really, sorry. There only exists some brief documentation here: https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html Otherwise, you currently have to browse the source code.

Got it, thank you!
