### ISSUE TITLE
can ur work process mutlti-dimensional(such as 3d) matrix multiplication?

### ISSUE THREAD

**Issue by irondachui** [rusty1s/pytorch_sparse#26]
hi, can your work can process multi-dimensional matrix multiplication like torch.matmul? For example, 
A is a i*j*k matrix,
B is a l*j matrix,
C=torch.matmul(B, A), 
in this case C is a i*l*k tensor. But it seems that your work can't do the same calculation, is that right?
`import torch
A = torch.randn(50, 60, 70)
B = torch.randn(40, 60)
C = torch.matmul(B, A)
C.size()
Out[5]: torch.Size([50, 40, 70])`

**Comment by rusty1s** [comment]
No, but you may can get around this problem by stacking your sparse matrices diagonally.
