### ISSUE TITLE
Sparse sparse element-wise operations e.g. add, multiply

### ISSUE THREAD

**Issue by shirley-wu** [rusty1s/pytorch_sparse#27]
Hi, could you implement sparse sparse element-wise operations such as add and multiply? Or could you point out ways to get around it? Thanks!

**Comment by rusty1s** [comment]
PyTorch sparse tensors support `add` and `multiply`, so I suggest to use those functions.

**Comment by rusty1s** [comment]
Although they are quite easy to implement on your own:
```python
row, col = index
mask = index[0]

**Comment by shirley-wu** [comment]
I don't tend to use pytorch sparse because their implementation is experimental; and it is inconvenient to convert values and tuples into sparse tensors, do calculations, and convert them back. I implemented multiply, which is even faster than Pytorch. Thanks for your reply!

**Comment by rusty1s** [comment]
Great that it is working, feel free to send a pull request if you like.

**Comment by Filco306** [comment]
Was this implemented? Is there an element-wise addition and multiplication for this package? :)

**Comment by rusty1s** [comment]
https://github.com/rusty1s/pytorch_sparse/issues/151#issuecomment-877091275
