### ISSUE TITLE
Slow sparse-sparse multiplication with SparseTensor format

### ISSUE THREAD

**Issue by realCrush** [rusty1s/pytorch_sparse#270]
Hi, I find it when doing sparse-sparse multiplication with `SparseTensor` format, the speed is super slow even compared with doing this with dense format.

The variable `s` and `adj_t` are both `SparseTensor`, and below is the info:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/57980447/187023516-eede8c10-9c42-4338-afc9-5d7360b76dd0.png">

Then I just do 10000 times sparse-sparse multiplication (to avoid noise) and got ~110s time usage:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/57980447/187023549-61814e53-9bf0-4a4f-b9bf-e50217d220b5.png">

The same computation with a simple `.to_dense()` making time usage decease to ~5s:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/57980447/187023590-ac06661e-6bab-4e84-b041-4f978509d83e.png">

Move the `to_dense()` out of for-loop, it becomes even faster (~3s):
<img width="552" alt="image" src="https://user-images.githubusercontent.com/57980447/187023607-b4e9b856-1d34-45bb-a516-4c5ef7ad6394.png">

I'm confusing because `SparseTensor` should be faster then dense format for such a very sparse tensor, this bug make my program really slow🥲, hope you can fix it

(All the above experiments are on an empty 3090 GPU card(without other program's disturbing).

**Comment by rusty1s** [comment]
Thanks for reporting! What is the timing when only running a single sparse-sparse matrix multiplication (e.g., `adj_t @ s`). My assumption is that the intermediate sparse matrix pretty dense, which might explain the overall slowdown. For example, you can also try to do
```python
s_t @ (adj_t @ s).to_dense()
```
We are utilizing `cusparse` internally for this, so there is sadly not much we can do to improve its efficiency :(

**Comment by realCrush** [comment]
> Thanks for reporting! What is the timing when only running a single sparse-sparse matrix multiplication (e.g., `adj_t @ s`)? My assumption is that the intermediate sparse matrix is pretty dense, which might explain the overall slowdown. You can also try to densify the intermediate representation:
> 
> ```python
> s_t @ (adj_t @ s).to_dense()
> ```
> 
> We are utilizing `cusparse` internally for this, so there is sadly not much we can do to improve its efficiency :(

It does becomes faster however still cost ~50s, and the result of `adj_t @ s` is also sparse (density=0.67%). Actually I found when doing SparseTensor@dense, it is really fast, and faster then SparseTensor.to_dense()@dense, I also tried to do the operations with `torch.sparse`, it is also slow and cost ~25s, this is wired since `SparseTensor` and `torch.sparse` are both designed for sparse tensors.

I want to ask is there a way to do sparse@sparse efficiently? I can't believe both SparseTensor@SparseTensor and torch.sparse@torch.sparse are so slow even compared with dense format🤪

![image](https://user-images.githubusercontent.com/57980447/187163712-2e00c2e7-335d-4ec0-b22f-ba1c6a1528f1.png)

**Comment by realCrush** [comment]
I leave two variables as .pkl here, you can try it:

[test.zip](https://github.com/rusty1s/pytorch_sparse/files/9443195/test.zip)

**Comment by rusty1s** [comment]
How dense is the final output? I think doing sparse-sparse matrix multiplication on GPUs efficiently is still an open problem. This is not really a GPU-friendly algorithm, as it involves non-contiguous access patterns and requires computing the number of NNZ entries in advance.

**Comment by realCrush** [comment]
> How dense is the final output? I think doing sparse-sparse matrix multiplication on GPUs efficiently is still an open problem. This is not really a GPU-friendly algorithm, as it involves non-contiguous access patterns and requires computing the number of NNZ entries in advance.

The final output is also sparse, with density=0.68%

![image](https://user-images.githubusercontent.com/57980447/187168001-e289ced4-a7ae-46c5-90ea-141ae1b49fd9.png)

**Comment by realCrush** [comment]
> This is not really a GPU-friendly algorithm

I also tried to do ot on CPU, and reduce time from ~110 to ~25:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/57980447/187170050-3d16a5a3-a540-4ca9-80a9-e38da5ab7af5.png">

**Comment by rusty1s** [comment]
If the CPU time is much faster than GPU times, I assume that your sparse matrices are too small to take advantages of the GPU here.

**Comment by rusty1s** [comment]
This should be resolved.
