### ISSUE TITLE
GCNConv (or any) fails for input of type SparseTensor. 

### ISSUE THREAD

**Issue by shash29-dev** [rusty1s/pytorch_sparse#275]
ASSUME a Pytorch geometric layer -
Layer(x, edge-index) <--- sucess
Sped= SparseTensor.from_edge_index(edge_index)
Layer(x,Sped) <--- Fails with Assertion

Why is this issue?

**Comment by rusty1s** [comment]
What is the error you encounter? :) This should definitely work.

**Comment by shash29-dev** [comment]
Hi,
I tried the same on linux, it runs, with sparse tensor.
While on windows,
Sparse tensor support fails with device side assert for input of type Sparsetensor.

**Comment by rusty1s** [comment]
Do you have a minimal example to reproduce? Does the same happen on CPU? At least in our CI, at least Windows CPU works fine.
