### ISSUE TITLE
benchmark py is reporting CUDA error: out of memory

### ISSUE THREAD

**Issue by Jinyaox** [rusty1s/pytorch_sparse#280]
I try to run the benchmark.py as it is and it kept reporting this message:
"RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect."

**Comment by rusty1s** [comment]
Can you show me the full output when running `benchmark/main.py`? How much GPU memory do you have?
