### ISSUE TITLE
RuntimeError: Not compiled with CUDA support

### ISSUE THREAD

**Issue by KS-spec** [rusty1s/pytorch_sparse#281]
Hi -,

I got the message:
RuntimeError: Not compiled with CUDA support
How should I do to fix it?
I have not any problem when I import torch_sparse.

Thanks,

File c:\Miniconda\envs\ocp-models102_2\lib\site-packages\torch_sparse\tensor.py:585, in __getitem__(self, index)
    583         dim += 1
    584     elif item.dtype == torch.long:
--> 585         out = out.index_select(dim, item)
    586         dim += 1
    587 elif item == Ellipsis:

File c:\Miniconda\envs\ocp-models102_2\lib\site-packages\torch_sparse\index_select.py:98, in <lambda>(self, dim, idx)
     92         value = value[idx]
     94     return SparseTensor(row=row, rowptr=None, col=col, value=value,
     95                         sparse_sizes=src.sparse_sizes(), is_sorted=True)
---> 98 SparseTensor.index_select = lambda self, dim, idx: index_select(self, dim, idx)
     99 tmp = lambda self, idx, layout=None: index_select_nnz(  # noqa
    100     self, idx, layout)
    101 SparseTensor.index_select_nnz = tmp

File c:\Miniconda\envs\ocp-models102_2\lib\site-packages\torch_sparse\index_select.py:15, in index_select(src, dim, idx)
     12 assert idx.dim() == 1
     14 if dim == 0:
---> 15     old_rowptr, col, value = src.csr()
     16     rowcount = src.storage.rowcount()
     18     rowcount = rowcount[idx]

File c:\Miniconda\envs\ocp-models102_2\lib\site-packages\torch_sparse\tensor.py:203, in SparseTensor.csr(self)
    202 def csr(self) -> Tuple[torch.Tensor, torch.Tensor, Optional[torch.Tensor]]:
--> 203     return self.storage.rowptr(), self.storage.col(), self.storage.value()

File c:\Miniconda\envs\ocp-models102_2\lib\site-packages\torch_sparse\storage.py:197, in SparseStorage.rowptr(self)
    195 row = self._row
    196 if row is not None:
--> 197     rowptr = torch.ops.torch_sparse.ind2ptr(row, self._sparse_sizes[0])
    198     self._rowptr = rowptr
    199     return rowptr

RuntimeError: Not compiled with CUDA support

**Comment by rusty1s** [comment]
How did you install `torch-sparse`? If you installed it from source, you can force CUDA installation via the `FORCE_CUDA=1` environment variable.

**Comment by KS-spec** [comment]
Thank you for your reply.
I have installed it via
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.2+cu102.html

**Comment by rusty1s** [comment]
Can you try to run
```
pip uninstall torch-sparse
pip uninstall torch-sparse
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.2+cu102.html
```

**Comment by KS-spec** [comment]
Thank you very much!
I could successfully install it.

**Comment by DanChai22** [comment]
> Can you try to run
> 
> ```
> pip uninstall torch-sparse
> pip uninstall torch-sparse
> pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.2+cu102.html
> ```
I install torch-sparse by
`pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.0+cu111.html`
Here is the error

> Looking in links: https://pytorch-geometric.com/whl/torch-1.10.0+cu111.html
> ERROR: Could not find a version that satisfies the requirement torch-sparse (from versions: none)
> ERROR: No matching distribution found for torch-sparse

**Comment by rusty1s** [comment]
Which python version are you using?
