### ISSUE TITLE
[Question] where does `torch.ops.torch_sparse` come from?

### ISSUE THREAD

**Issue by q-aaronzolnailucas** [rusty1s/pytorch_sparse#284]
Trying to dive into how sparse-sparse matrix multiplication is working but I can't figure out where this import comes from, if I try importing it in a notebook with `torch` and `torch_sparse` imported I get an import error, but I see it's used in the source code of `matmul.py`. Where does this come from?

**Comment by rusty1s** [comment]
The implementation of spspmm is [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/spmm_cpu.cpp) (CPU) and [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cuda/spspmm_cuda.cu) (GPU). For GPU, we make use of `cusparse` routines, while we implement our own simple variant for CPU-processing.

**Comment by rusty1s** [comment]
What's the issue you experience? Happy to help with installation :)
