### ISSUE TITLE
Wheels for torch-1.13.0

### ISSUE THREAD

**Issue by m-naumann** [rusty1s/pytorch_sparse#288]
Hi @rusty1s,

To have it trackable, I created this issue for https://github.com/rusty1s/pytorch_sparse/pull/272#issuecomment-1305662121:

> Could you release with this fix merged @rusty1s? It looks like this comes from
> 
> [pytorch/pytorch@4f34cd6#diff-5e5c8e86c569dfad25dd3c6ee122031da882781c44f7f0a3a32bbebe9103f12bL147](https://github.com/pytorch/pytorch/commit/4f34cd6d1e91dcd82ee30c3ea39bdb8a0fa93e8b#diff-5e5c8e86c569dfad25dd3c6ee122031da882781c44f7f0a3a32bbebe9103f12bL147)
> 
> from torch-1.12.1 to torch-1.13.0, i.e. the currently most recent torch-sparse-0.6.15 is incompatible with torch-1.13.0

Thanks 🙏

**Comment by m-naumann** [comment]
@rusty1s is there anything I can do to support?

**Comment by rusty1s** [comment]
Sorry, missed this issue. Wheels for PyTorch 1.13 or available. Anything else needed to resolve?

**Comment by m-naumann** [comment]
No worries! For me, 0.6.15 is still the latest release in this repo and on pypi: https://pypi.org/project/torch-sparse/ and I'd need a new release for torch 1.13, or am I missing something?

**Comment by rusty1s** [comment]
I just created a 0.6.15 wheel for PyTorch 1.13.

**Comment by m-naumann** [comment]
Thanks for the new release 😃
