### ISSUE TITLE
Can I use sparsetensor as a nn.Parameter and move it to device? 

### ISSUE THREAD

**Issue by Chengwei94** [rusty1s/pytorch_sparse#289]
Hi there, 

I was looking at this thread and see that we can use sparse matrix as a nn.Parameter. However, I wasnt sure on how to move it to the device since only the values move to cuda when I use .to(device), while the sparsetensor stayed at the cpu. Thanks!

https://github.com/rusty1s/pytorch_sparse/issues/151

**Comment by rusty1s** [comment]
You can do
```python
self.register_buffer('row', torch.tensor(...))
self.register_buffer('col', torch.tensor(...))
self.value = torch.nn.Parameter(torch.tensor(...))

def forward(self, ...):
   mat = SparseTensor(row=self.row, col=self.col, value=self.value)
```
