### ISSUE TITLE
after i installed PyTorch 1.2. its ok when i use PyTorch 1.1

### ISSUE THREAD

**Issue by xh22** [rusty1s/pytorch_sparse#29]
miniconda3/lib/python3.6/site-packages/torch_sparse/unique_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv

**Comment by rusty1s** [comment]
I do not understand the question. Do you use PyTorch 1.2 or 1.1? This extension package only works for the respective PyTorch version it is installed with.

**Comment by xh22** [comment]
It works fine with PyTorch 1.2 now after i reinstalled pytorch_sparse, I guess the problem is i updated PyTorch 1.1 to PyTorch 1.2 but not reinstall pytorch_sparse? 
So symbol:_ZN3c106Device8validateEv changed some how?
anyway solved the problem,many thanks!
