### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by kochbj** [rusty1s/pytorch_sparse#30]
Same issue is found in the torch-scatter package:
Ubuntu 18.04
Cuda 9.0.176
Torch 1.1 (matching Cuda)

`  /usr/include/c++/6/type_traits:1558:8: note: provided for ‘template<class _From, class _To> struct std::is_convertible’
       struct is_convertible
          ^~~~~~~~~~~~~~
  /usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, double, long int>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, double, long int}]’ not a return-statement
       }
   ^
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1`

**Comment by rusty1s** [comment]
Closed in favor of https://github.com/rusty1s/pytorch_scatter/issues/68.
