### ISSUE TITLE
I am building a package with pytorch-sparse

### ISSUE THREAD

**Issue by cap-jmk** [rusty1s/pytorch_sparse#307]
Hey, when I am building a package with `torch-sparse` and PyTorch, there is a dependency conflict. 

The error is probably due to a missing build dependency. Maybe the discovery from the setuptools does not work in that way, too. 
Do you have an idea on how to solve the error? It would mean a lot to be able to ship my package via PyPi.

Compare the error message: 
```bash 
Collecting torch-sparse
  Using cached torch_sparse-0.6.16.tar.gz (208 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-29a0cpik/torch-sparse_8674363281864c7780825e736f6d18ba/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rusty1s** [comment]
If you compile `torch-sparse` from source, it will need to find PyTorch in order to compile it. The only workaround right now is to point `torch-sparse` installation to the provided wheels, in which case PyTorch does not need to be installed. As such, I would suggest to make `torch-sparse` an optional dependency in your package, and then just point the user to the README on how to install. Would that work for you?

**Comment by cap-jmk** [comment]
I will give it a try.

**Comment by cap-jmk** [comment]
I could solve it with some modifications in the pyproject.toml. You may consider them, too. 

```yaml
[build-system]
requires = ["setuptools","torch"]
build-backend = "setuptools.build_meta"

[project]
.
.
.
dependencies = [
    "torch",
    ...]

```
