### ISSUE TITLE
RuntimeError: derivative for aten::_coalesced_ is not implemented

### ISSUE THREAD

**Issue by ramanshsharma2806** [rusty1s/pytorch_sparse#310]
I am getting this error:
``RuntimeError: derivative for aten::_coalesced_ is not implemented``
when I am trying to apply ``torch.autograd.grad`` on `spmm(idx, values, n, m, mat).diagonal().unsqueeze(1)   ` w.r.t. an input tensor that made the sparse tensor.

Can anyone please help me fix this?

**Comment by rusty1s** [comment]
Do you have a small script to reproduce?

**Comment by ramanshsharma2806** [comment]
Yes, sorry for not including it before.

```
from torch_sparse import spmm
import torch
from torch.autograd import grad

x = torch.rand(3, 1).requires_grad_(True)

sparse_mat = x ** 2 + x # sparse_mat is some function of x
sparse_mat = sparse_mat.requires_grad_(True).to_sparse_coo()

# sparse_mat is of shape (3, 1)

dense_mat = x ** 3 # dense_mat is also a function of x
dense_mat = dense_mat.transpose(1, 0).requires_grad_(True)

# dense_mat is of shape (1, 3)

idx = sparse_mat.indices()
values = sparse_mat.values()
n, m = sparse_mat.shape

# multiply sparse_mat with dense_mat
output = spmm(idx, values, n, m, dense_mat).diagonal().unsqueeze(1)

# output is of shape (3, 1)

output_x = grad(output, x, grad_outputs=torch.ones_like(output), create_graph=True)[0]
output_xx = grad(output_x, x, grad_outputs=torch.ones_like(output), create_graph=True)[0]

```

``output_x`` is computed without any problem. But the line which computes ``output_xx`` results in the error.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/24642071/218294140-85c53c57-6a44-4808-bf53-39771fdf4eb6.png">

**Comment by rusty1s** [comment]
There seems to be an issue that PyTorch cannot maintain gradients from dense to COO conversion. I think in your case, this is fixable by just creating `index` and `values` from the dense matrix directly:
```python
x = torch.rand(3, 1).requires_grad_(True)

sparse_mat = x**2 + x  # sparse_mat is some function of x
idx = sparse_mat.nonzero().t()
values = sparse_mat[idx[0], idx[1]]

dense_mat = x**3  # dense_mat is also a function of x
dense_mat = dense_mat.transpose(1, 0).requires_grad_(True)

n, m = sparse_mat.shape

# multiply sparse_mat with dense_mat
output = spmm(idx, values, n, m, dense_mat).diagonal().unsqueeze(1)

output_x = grad(output, x, grad_outputs=torch.ones_like(output),
                create_graph=True)[0]
output_xx = grad(output_x, x, grad_outputs=torch.ones_like(output),
                 create_graph=True)[0]

**Comment by ramanshsharma2806** [comment]
Thank you so much for your reply! I really appreciate it. In the code you suggested, I am getting an error with this line:

```python
idx = sparse_mat.nonzero().t()
```

The error I get is ``NotImplementedError: Could not run 'aten::nonzero' with arguments from the 'SparseCPU' backend. ``.

I also tried to use this with the `sparse_mat` tensor being on CUDA, then the error was:
`NotImplementedError: Could not run 'aten::nonzero' with arguments from the 'SparseCUDA' backend.`

Is this line working normally for you?

**Comment by ramanshsharma2806** [comment]
Ah wait, I see why I got the error. You applied the `.nonzero().t()` on the dense matrix since the sparse_coo one doesn't have it implemented. I will try that right now.

**Comment by ramanshsharma2806** [comment]
It works, thank you so much for your help!!
