### ISSUE TITLE
How to use sparsetensor mask sparsetensor

### ISSUE THREAD

**Issue by GooLiang** [rusty1s/pytorch_sparse#313]
Hi!
I have two sparse tensors A and B. I want to use B to mask A. 
The masked_select.py only support tensor mask sparse tenor. 
Thanks!

**Comment by rusty1s** [comment]
This is a non-trivial problem as you need to find the overlap between `B` and `A`. One way to solve this what be to operate on the indices directly, and use `torch.isin` logic to find the overlap:
```python
rowA, colA, _ = A.coo()
rowB, colB, _ = B.coo()

indexA = rowA * num_cols + colA
indexB = rowB * num_cols + colB

nnz_mask = indexA.isin(indexB)

**Comment by GooLiang** [comment]
Thanks for the reply, it seems that I did not express it clearly. I already have a mask generated from B, and I want to replace the corresponding position of A with this mask. For example, as shown in the figure, I want to replace the position where the mask is True with the corresponding position in A and set it to 0.

A
SparseTensor(row=tensor([   0,    0,    0,  ..., 3022, 3023, 3024]),
             col=tensor([   0,    2,    4,  ..., 3022, 3023, 3024]),
             val=tensor([0.1186, 0.0179, 0.0043,  ..., 0.3750, 1.0000, 1.0000]),
             size=(3025, 3025), nnz=74671, density=0.82%)
mask
SparseTensor(row=tensor([   0,    0,    0,  ..., 3022, 3023, 3024]),
             col=tensor([   0,  179,  526,  ..., 3022, 3023, 3024]),
             val=tensor([True, True, True,  ..., True, True, True]),
             size=(3025, 3025), nnz=13645, density=0.15%)

**Comment by GooLiang** [comment]
Thanks for your help, the problem has been solved, the solution is the same as you said.
