### ISSUE TITLE
Seems don't apply to my case

### ISSUE THREAD

**Issue by lixinghe1999** [rusty1s/pytorch_sparse#316]
Dear authors and others,

Currently, I encounter one problem. Below is the illustration:
![illustrate_page-0001](https://user-images.githubusercontent.com/60444469/225207052-241a03ae-ee88-497b-90b3-9d4dbfa8e9a6.jpg)
I have tested pytorch_sparse on my case with some dummy input, however, the latency is not good.
I guess pytorch_sparse may only apply to very sparse matrix, however, my matrix is only 50% sparse.

Are there any one can point out my misunderstanding if there is any?
Or, if pytorch_sparse is not a good tool, are there any other library for this problem?
Thanks a lot in advance.

**Comment by rusty1s** [comment]
That is correct. In your case, something like a "block sparse matrix" layout may be more fitting.
