### ISSUE TITLE
Can not install torch-sparse. GCC Error 

### ISSUE THREAD

**Issue by ndthmdg98** [rusty1s/pytorch_sparse#318]
When I try to install torch-sparse I get the following error:

>   Running setup.py install for torch-sparse ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/username/SoftwareProjekte/nnn_sandbox/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-install-3jl5jifi/torch-sparse/setup.py'"'"'; __file__='"'"'/private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-install-3jl5jifi/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-record-qgg3b_3f/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/SoftwareProjekte/nnn_sandbox/venv/include/site/python3.9/torch-sparse
         cwd: /private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-install-3jl5jifi/torch-sparse/
    Complete output (123 lines):
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    Compiling without OpenMP...
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/matmul.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/permute.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/add.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/reduce.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/narrow.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/masked_select.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/cat.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/eye.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/convert.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/coalesce.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/tensor.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/bandwidth.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/mul.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/transpose.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/utils.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/diag.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/rw.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/storage.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/sample.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/spspmm.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/index_select.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/saint.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/select.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/spadd.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/testing.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/spmm.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    copying torch_sparse/metis.py -> build/lib.macosx-10.9-x86_64-3.9/torch_sparse
    running egg_info
    writing torch_sparse.egg-info/PKG-INFO
    writing dependency_links to torch_sparse.egg-info/dependency_links.txt
    writing requirements to torch_sparse.egg-info/requires.txt
    writing top-level names to torch_sparse.egg-info/top_level.txt
    reading manifest file 'torch_sparse.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/css'
    warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/html'
    warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/tests'
    warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/examples'
    warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/benchmark'
    warning: no previously-included files matching '*' found under directory 'test'
    warning: no previously-included files matching '*' found under directory 'benchmark'
    writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
    running build_ext
    building 'torch_sparse._relabel_cpu' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/csrc
    creating build/temp.macosx-10.9-x86_64-3.9/csrc/cpu
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DWITH_PYTHON -Icsrc -Ithird_party/parallel-hashmap -I/Users/username/SoftwareProjekte/nnn_sandbox/venv/lib/python3.9/site-packages/torch/include -I/Users/username/SoftwareProjekte/nnn_sandbox/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/Users/username/SoftwareProjekte/nnn_sandbox/venv/lib/python3.9/site-packages/torch/include/TH -I/Users/username/SoftwareProjekte/nnn_sandbox/venv/lib/python3.9/site-packages/torch/include/THC -I/Users/username/SoftwareProjekte/nnn_sandbox/venv/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c csrc/cpu/relabel_cpu.cpp -o build/temp.macosx-10.9-x86_64-3.9/csrc/cpu/relabel_cpu.o -O3 -Wno-sign-compare -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_clang" -DPYBIND11_STDLIB="_libcpp" -DPYBIND11_BUILD_ABI="_cxxabi1002" -DTORCH_EXTENSION_NAME=_relabel_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5142:58: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
        class  LockableImpl<std::shared_mutex> : public std::shared_mutex
                                                             ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5145:38: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
            using mutex_type      = std::shared_mutex;
                                         ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5146:55: error: 'shared_mutex' is unavailable: introduced in macOS 10.12
            using Base            = LockableBaseImpl<std::shared_mutex>;
                                                          ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5147:50: error: 'mutex_type' is unavailable: introduced in macOS 10.12
            using SharedLock      = std::shared_lock<mutex_type>;
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5148:50: error: 'mutex_type' is unavailable: introduced in macOS 10.12
            using UpgradeLock     = std::unique_lock<mutex_type>; // assume can't upgrade
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    In file included from csrc/cpu/relabel_cpu.cpp:3:
    In file included from csrc/cpu/utils.h:4:
    In file included from third_party/parallel-hashmap/parallel_hashmap/phmap.h:121:
    third_party/parallel-hashmap/parallel_hashmap/phmap_base.h:5149:50: error: 'mutex_type' is unavailable: introduced in macOS 10.12
            using UniqueLock      = std::unique_lock<mutex_type>;
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/shared_mutex:180:58: note: 'shared_mutex' has been explicitly marked unavailable here
    class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_SHARED_MUTEX shared_mutex
                                                             ^
    6 errors generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/username/SoftwareProjekte/nnn_sandbox/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-install-3jl5jifi/torch-sparse/setup.py'"'"'; __file__='"'"'/private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-install-3jl5jifi/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pt/nkwzf_n165n5ftp5jj0z9lxr0000gn/T/pip-record-qgg3b_3f/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/SoftwareProjekte/nnn_sandbox/venv/include/site/python3.9/torch-sparse Check the logs for full command output.

Setup:

**MacBook Pro 16" 2019 | MacOS Ventura 13.2.1**

**python version**
    3.9

**gcc version**:
    Apple clang version 14.0.0 (clang-1400.0.29.202)
    Target: x86_64-apple-darwin22.3.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**installed torch packages**:
    torch==2.0.0
    torch-cluster==1.6.1
    torch-geometric==2.2.0
    torch-scatter==2.1.1
    torch-spline-conv==1.2.2
    torchaudio==2.0.1
    torchvision==0.15.1

**Comment by rusty1s** [comment]
Should be fixed once #320 is merged.
