### ISSUE TITLE
RandomWalk Algorithm Does not account for nodes with no connections

### ISSUE THREAD

**Issue by ProfDoof** [rusty1s/pytorch_sparse#324]
https://github.com/rusty1s/pytorch_sparse/blob/13d7a2cb44661fd38f9ca36607ff831c9234d5f1/csrc/cpu/rw_cpu.cpp#L27-L42

Hi! I was using the random_walk implementation to hopefully speed up my code but noticed that the random walk implementation does not account for when the node does not have any further connections. The tests I ran with it seem to have it jump to a new node (it's not random though) or just sit in one place stuck. That may be because of a self-loop but I'm not sure, I did not have my visualization code prepped at the time. I'm not sure what a reasonable default behavior is though. Is the reasonable default behavior to just stay in place? That would make sense to me but it should definitely be written down on the random walk implementation.

Anyway, if there's a simple accepted solution to this, I would appreciate it, otherwise, I'll probably try to hack together a solution involving something like self-loops (though I don't really like the chance of randomly walking back to yourself, it's not quite right for my use case)

**Comment by rusty1s** [comment]
The `torch-sparse` implementation does not account for this, as it expects non-isolated nodes. We have a more advanced implementation in `pyg-lib`, which will add a self-loop in this case, see https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/csrc/sampler/cpu/random_walk_kernel.cpp

**Comment by ProfDoof** [comment]
Thanks!
