### ISSUE TITLE
Separate extension per cpp file impedes parallel compilation

### ISSUE THREAD

**Issue by ezyang** [rusty1s/pytorch_sparse#326]
I noticed that setup.py was building sequentially, and sent a PR https://github.com/rusty1s/pytorch_sparse/pull/325 to fix ninja use. However, even with ninja, it is still building sequentially. The reason is that we define a CppExtension per cpp file, and setuptools will build these serially. If we bundled all of the cpp files into a single CppExtension, ninja would be able to build them in parallel, for a lot of speedup.

**Comment by rusty1s** [comment]
I don't think this problem is present in `pyg-lib` as we are building a single extension there already.
