### ISSUE TITLE
what is the `non_blocking` parameter in `SparseTensor` class

### ISSUE THREAD

**Issue by Barcavin** [rusty1s/pytorch_sparse#333]
What is the `non_blocking` parameter in `SparseTensor` class and how can it affect the data storage of the class?

I am trying to find the documentation but failed so

**Comment by rusty1s** [comment]
If the data is in pinned memory, you can use `to(device, non_blocking=True)` for asynchronous device transfers (similar to [`torch.Tensor.to()`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html?highlight=#torch.Tensor.to)).

**Comment by Barcavin** [comment]
Thanks a lot!
