### ISSUE TITLE
Meaning of out_root_n_id in script csrc/cpu/ego_sample_cpu.cpp

### ISSUE THREAD

**Issue by zhaoqf123** [rusty1s/pytorch_sparse#337]
May I know what's the meaning of `out_root_n_id` in `csrc/cpu/ego_sample_cpu.cpp`?

I thought it was the original node-id of the raw big graph, but after testing, it's not.

Could you please explain it a bit?

Thank you.

**Comment by zhaoqf123** [comment]
> May I know what's the meaning of `out_root_n_id` in `csrc/cpu/ego_sample_cpu.cpp`?
> 
> I thought it was the original node-id of the raw big graph, but after testing, it's not.
> 
> Could you please explain it a bit?
> 
> Thank you.

I just got it. It means the `out_root_n_id`-th node in the subgraph is the ego-node!

**Comment by rusty1s** [comment]
Yes, exactly :)
