### ISSUE TITLE
gcc installation error with OSX 10.14.6, python 3.7, conda 4.7.12

### ISSUE THREAD

**Issue by jonberliner** [rusty1s/pytorch_sparse#34]
install failed with error 
```
 error: command 'gcc' failed with exit status 1
```

I already had XCode and brew gcc installed.

Resolved error by installing with:

`alias clang='CFLAGS="-stdlib=libc++" CC=clang CXX=clang $1 pip install torch-scatter torch-sparse` as suggested [here](https://github.com/ICB-DCM/AMICI/issues/357#issuecomment-407779967).

**Comment by Haicang** [comment]
I got a similar installation error (probably the same) on Mac:

>                                    !! WARNING !!
> 
>     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     Your compiler (g++) is not compatible with the compiler Pytorch was
>     built with for this platform, which is clang++ on darwin. Please
>     use clang++ to to compile your extension. Alternatively, you may
>     compile PyTorch from source using g++, and then you can also use
>     g++ to compile your extension.
> 
>     See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
>     with compiling PyTorch from source.
>     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
>                                   !! WARNING !!
> (from `torch/utils/cpp_extension.py:191: UserWarning:`)
>
> error: command 'gcc' failed with exit status 1

I solve this problem by:
`MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ pip install torch-sparse`,
where `MACOSX_DEPLOYMENT_TARGET` is the MacOS version, e.g. 10.15 for Catalina.
