### ISSUE TITLE
node_weight for balanced edge in metis partition

### ISSUE THREAD

**Issue by zhaoqf123** [rusty1s/pytorch_sparse#341]
https://github.com/rusty1s/pytorch_sparse/blob/14781cb04e4555859980755b7b17240209c34b4a/torch_sparse/metis.py#L55

Here, `node_weight = col.new_zeros(col.size(0))` has wrong shape. It should be `torch.zeros(num_nodes, dtype=col.dtype)`, otherwise the assertion `assert node_weight.numel() == rowptr.numel() - 1` in L59 would get error.

**Comment by rusty1s** [comment]
Thanks, will be fixed in https://github.com/rusty1s/pytorch_sparse/pull/342.
