### ISSUE TITLE
can`t install torch-sparse

### ISSUE THREAD

**Issue by gzdshqt** [rusty1s/pytorch_sparse#35]
Hi. Though i have try many time  ,i still can`t install torch-sparse.

It says that:
Running setup.py install for torch-sparse ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\56784\AppData\Local\conda\conda\envs\my_root\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-pp8x8xof\\torch-sparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-pp8x8xof\\torch-sparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\56784\AppData\Local\Temp\pip-record-y00on3tr\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\56784\AppData\Local\Temp\pip-install-pp8x8xof\torch-sparse\
    Complete output (53 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\test
    copying test\test_coalesce.py -> build\lib.win-amd64-3.6\test
    copying test\test_convert.py -> build\lib.win-amd64-3.6\test
    copying test\test_eye.py -> build\lib.win-amd64-3.6\test
    copying test\test_spmm.py -> build\lib.win-amd64-3.6\test
    copying test\test_spspmm.py -> build\lib.win-amd64-3.6\test
    copying test\test_spspmm_spmm.py -> build\lib.win-amd64-3.6\test
    copying test\test_transpose.py -> build\lib.win-amd64-3.6\test
    copying test\utils.py -> build\lib.win-amd64-3.6\test
    copying test\__init__.py -> build\lib.win-amd64-3.6\test
    creating build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\coalesce.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\convert.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\eye.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\spmm.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\spspmm.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\transpose.py -> build\lib.win-amd64-3.6\torch_sparse
    copying torch_sparse\__init__.py -> build\lib.win-amd64-3.6\torch_sparse
    creating build\lib.win-amd64-3.6\torch_sparse\utils
    copying torch_sparse\utils\unique.py -> build\lib.win-amd64-3.6\torch_sparse\utils
    copying torch_sparse\utils\__init__.py -> build\lib.win-amd64-3.6\torch_sparse\utils
    running build_ext
    C:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\utils\cpp_extension.py:88: UserWarning: Error checking compiler version: [WinError 2] 系统找不到指定的文件。
      warnings.warn('Error checking compiler version: {}'.format(error))
    C:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\utils\cpp_extension.py:114: UserWarning:
    
                                   !! WARNING !!
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (cl) may be ABI-incompatible with PyTorch!
    Please use a compiler that is ABI-compatible with GCC 4.9 and above.
    See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
    
    See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
    for instructions on how to install GCC 4.9 or higher.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
                                  !! WARNING !!
    
      warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
    building 'torch_sparse.spspmm_cpu' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cpu
    D:\Program Files\visual\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\lib\include -IC:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\lib\include\TH -IC:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\lib\include\THC -IC:\Users\56784\AppData\Local\conda\conda\envs\my_root\include -IC:\Users\56784\AppData\Local\conda\conda\envs\my_root\include "-ID:\Program Files\visual\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-ID:\Program Files\visual\VC\Tools\MSVC\14.22.27905\include" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpcpu/spspmm.cpp /Fobuild\temp.win-amd64-3.6\Release\cpu/spspmm.obj -DTORCH_EXTENSION_NAME=spspmm_cpu
    spspmm.cpp
    cpu/spspmm.cpp(1): fatal error C1083: 无法打开包括文件: “torch/extension.h”: No such file or director
y
    error: command 'D:\\Program Files\\visual\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\56784\AppData\Local\conda\conda\envs\my_root\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-pp8x8xof\\torch-sparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-pp8x8xof\\torch-sparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\56784\AppData\Local\Temp\pip-record-y00on3tr\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rusty1s** [comment]
Are you sure you are using PyTorch >= 1.2?

**Comment by gzdshqt** [comment]
I have updated my Pytorch to 1.2.0
my environments as follow
OS: windows 10
Python version: 3.6.4
PyTorch version: 1.2.0
CUDA/cuDNN version: 10.1

However, I get new error

File "C:\Users\56784\AppData\Local\conda\conda\envs\my_root\lib\site-packages\torch\cuda\__init__.py", line 95, in _check_driver
        raise AssertionError("Torch not compiled with CUDA enabled")
    AssertionError: Torch not compiled with CUDA enabled
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\56784\AppData\Local\conda\conda\envs\my_root\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-1b5714e4\\torch-sparse\\setup.py'"'"'; __file__='"'"'C:\\Users\\56784\\AppData\\Local\\Temp\\pip-install-1b5714e4\\torch-sparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\56784\AppData\Local\Temp\pip-record-tzaj85m7\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rusty1s** [comment]
Well, it seems that you did not install PyTorch with CUDA support.

**Comment by snyguy** [comment]
Having trouble with CUDA10.2. Is this for a previous version of CUDA?

**Comment by rusty1s** [comment]
Please try the new Python wheels for a smoother installation :) See the README for instructions.

**Comment by snyguy** [comment]
That worked, but then ran into a W10 DLL issue.
https://github.com/rusty1s/pytorch_geometric/issues/970
