### ISSUE TITLE
"OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found" with torch-sparse 0.6.18+pt20cu118

### ISSUE THREAD

**Issue by NotTodayNotMe** [rusty1s/pytorch_sparse#351]
* PyG version: 2.1.0
* PyTorch version: 2.1.0
* OS: RockyLinus 8.8
* Python version: 3.10.13
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source):  conda

Hi team, 

The pyg is working well but I got this issue when trying to install pytorch-sparse:
 
```
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /srv/scratch/z5328320/miniconda3/lib/python3.10/site-packages/torch_sparse/_metis_cuda.so)
```

I cannot update GLIBC to 2.29 because I'm working on a HPC with some GPU nodes and the GLIBC verion is fixed to 2.28 on RockyLinux 8.8.

I also tried ` pip install --verbose pytorch_sparse` but finally fall into a CPU version and cannot match my pyg.

Besides, I failed to install pytorch-sparse from source as well.

python setup.py install

running install
/srv/scratch/z5328320/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/srv/scratch/z5328320/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating torch_sparse.egg-info
writing torch_sparse.egg-info/PKG-INFO
writing dependency_links to torch_sparse.egg-info/dependency_links.txt
writing requirements to torch_sparse.egg-info/requires.txt
writing top-level names to torch_sparse.egg-info/top_level.txt
writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
reading manifest file 'torch_sparse.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'third_party'
warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/css'
warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/html'
warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/tests'
warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/examples'
warning: no previously-included files matching '*' found under directory 'third_party/parallel-hashmap/benchmark'
warning: no previously-included files matching '*' found under directory 'benchmark'
adding license file 'LICENSE'
writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/__init__.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/add.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/bandwidth.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/cat.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/convert.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/diag.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/eye.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/index_select.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/masked_select.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/matmul.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/metis.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/mul.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/narrow.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/permute.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/reduce.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/rw.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/saint.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/sample.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/select.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/spadd.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/spmm.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/storage.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/tensor.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/testing.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/transpose.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/typing.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
copying torch_sparse/utils.py -> build/lib.linux-x86_64-cpython-310/torch_sparse
running build_ext
/srv/scratch/z5328320/miniconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'torch_sparse._convert_cpu' extension
creating /home/z5328320/PSHGCN/hgb/pytorch_sparse/build/temp.linux-x86_64-cpython-310
creating /home/z5328320/PSHGCN/hgb/pytorch_sparse/build/temp.linux-x86_64-cpython-310/csrc
creating /home/z5328320/PSHGCN/hgb/pytorch_sparse/build/temp.linux-x86_64-cpython-310/csrc/cpu
Emitting ninja build file /home/z5328320/PSHGCN/hgb/pytorch_sparse/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
```

Looking for your help.

Regards,
Levius

**Comment by rusty1s** [comment]
Thanks for reporting. I track progress of this here: https://github.com/pyg-team/pytorch_geometric/issues/8217

Closing this to avoid duplicates.
