### ISSUE TITLE
Time complexity of Sparse Sparse Matrix Multiplication?

### ISSUE THREAD

**Issue by RongqinChen** [rusty1s/pytorch_sparse#352]
Dear authors,
Thank you for developing such a great library.
I'm writing to ask about the time complexity of the sparse-sparse matrix multiplication implemented in this library. Suppose the sizes of the two sparse matrices are $n \times n$ and the numbers of non-zero elements in them are both $m$.

Best wishes.
Ron

**Comment by rusty1s** [comment]
We are using `cusparse` internally for SpSpMM, which does not have a open-source implementation available, so I don't know about the time complexity.
