### ISSUE TITLE
Batch in spspmm?

### ISSUE THREAD

**Issue by iminfine** [rusty1s/pytorch_sparse#357]
Can make spspmm support also 3D tensor (might think as batched):
suppose one sparse matrix has dimensions (B, M, N), the other has dimensions (B, N, F)
and the multiplication result has dimensions (B,M,F)?

**Comment by rusty1s** [comment]
No that's not possible. I suggest do stack your matrices diagonal and perform classic two-dimensional `spspmm`.

**Comment by iminfine** [comment]
Thank you for your prompt response. 
Could you please provide further elaboration on the details of your recommendations?

**Comment by rusty1s** [comment]
If you stack the matrices diagonally, they have shape `[B*M, B*N] @ [B*N, B*F]`, which results in an output of shape `[B*M, B*F]`, which you can then "reshape" back to `[B, M, F]`. Implementation-wise, this would be
```python
from torch_sparse import cat

mats1 = [SparseTensor(...), SparseTensor(...), ...]
mats2 = [SparseTensor(...), SparseTensor(...), ...]

mat1 = cat(mats1, dim=(0, 1))
mat2 = cat(mats2, dim=(0, 1))

out = mat1 @ mat2

**Comment by iminfine** [comment]
Thanks
