### ISSUE TITLE
Is there a convenient way to Substract two vectors?

### ISSUE THREAD

**Issue by KukumavMozolo** [rusty1s/pytorch_sparse#358]
Hi there, thank you for this project!
I am trying to subtract two sparse vectors from each other and I have not found a convenient way to do so.

What would be the most memory efficient way of doing that?

**Comment by rusty1s** [comment]
`SparseTensor + SparseTensor` should be supported in the latest release, so I would assume you can just do `mat1 + mat.mul_nnz(-1)`. There doesn't exist a more convenient call for this right now :(

**Comment by KukumavMozolo** [comment]
That looks a lot better then what i was doing, thanks a lot!
