### ISSUE TITLE
High dimensional Sparse Matrix Multiplication

### ISSUE THREAD

**Issue by yonatansverdlov** [rusty1s/pytorch_sparse#361]
Hi, there
I have a tensor ten1 of shape [b,n,dim,i] which is sparse, and ten2 tensor of shape [i,m] and I want to output ten1@ten2 of shape [b,n,dim,m], how can I use the library functions?
Thanks!

**Comment by rusty1s** [comment]
See my answer in https://github.com/rusty1s/pytorch_sparse/issues/248#issuecomment-1919703165.
