### ISSUE TITLE
Factorization?

### ISSUE THREAD

**Issue by Sentient07** [rusty1s/pytorch_sparse#363]
Hi,

I was wondering if you'd provide LU/Cholesky/QR factorization for sparse matrices? https://github.com/rgl-epfl/cholespy library provides for cholesky but one would need PD matrices. If I'd want to do LU, I still have to do to_dense() and use `torch.lu()` which isn't optimal. Hence, was wondering if it could be done using pytorch_sparse? Thanks!

**Comment by rusty1s** [comment]
Thanks for the issue. We currently don't have any plans to support such operations in our library.
