### ISSUE TITLE
SparseTensor or SparseStorage for data

### ISSUE THREAD

**Issue by Xparx** [rusty1s/pytorch_sparse#365]
Hello,

I recently found this package. This is a great library and very promising. Thank you for the great work!

I am trying to figure out what modules or classes to use in what situation. I want to store high dimensional data as a sparse matrix and sample during training etc.
I am wondering what format to use. I have seen SparseTensor and SparseStorage and I wonder what format is the best suited for my case of having large sparse data when it comes to e.g. sampling and batching.

**Comment by Xparx** [comment]
Just noticed that `SparseTensor` use `SparseStorage` internally so assuming that `SparseTensor` is SparseStorage with some extra flourish.

**Comment by rusty1s** [comment]
Yes, `SparseTensor` unifies COO/CSR/CSC in a single representation, so access to either of them is fast.

**Comment by rusty1s** [comment]
Only via diagonal stacking (i.e., `cat(adjs, dim=(0, 1))`.

**Comment by Xparx** [comment]
got it. Thanks for the answer.
