### ISSUE TITLE
Sparse Bilinear map

### ISSUE THREAD

**Issue by Xparx** [rusty1s/pytorch_sparse#369]
Hey,

I'm trying to implement a custom attention mechanism. 
Is there a function or a efficient way to implement a bilinear mapping in `pytorch_sparse`?

**Comment by rusty1s** [comment]
Can you clarify what you wan to do exactly?

**Comment by Xparx** [comment]
I wanted to try to do the same as in the pytorch [bilinear](https://pytorch.org/docs/stable/generated/torch.nn.Bilinear.html) module, when `A` is a sparse matrix.

**Comment by Xparx** [comment]
As far as I understand `pytorch_sparse` works on 2d tensors so might not be relevant exactly. I might need to think this one over a bit.

**Comment by rusty1s** [comment]
`torch-sparse` can handle more than 2 dimensions (but only the first two can be sparse). Would that be sufficient in your case?

**Comment by Xparx** [comment]
Hey, Sorry for the slow response. I think my problem and my understanding of what is being computed doesn't make sense. 
I manage to use `torch-sparse` for the sparse computations I needed. 
I'm going to close this issue for now.

Thanks for the great library!
