### ISSUE TITLE
Max operation not working in coalesce with negative values

### ISSUE THREAD

**Issue by sbagchi12** [rusty1s/pytorch_sparse#37]
Why does the max operation between negative values give 0 instead of the max of the negative numbers?

Here is the code snippet:

import torch
from torch_sparse import coalesce

index = torch.tensor([[1, 0, 1, 0, 2, 1],
                      [0, 1, 1, 1, 0, 0]])
value = torch.Tensor([[-11], [-2], [-3], [-4], [-5], [-6]])
value = value.type(torch.float)

index, value = coalesce(index, value, m=3, n=2,op="max")
print(index)
print(value)

Output:

tensor([[0, 1, 1, 2],
        [1, 0, 1, 0]])
tensor([[0.],
        [0.],
        [0.],
        [0.]])

**Comment by rusty1s** [comment]
Try setting the `fill_value` of the `coalesce` function to a large negative number :)

**Comment by sbagchi12** [comment]
Thanks
