### ISSUE TITLE
torch_sparse.tensor.SparseTensor.partition causes "core dumped"

### ISSUE THREAD

**Issue by AaronNing** [rusty1s/pytorch_sparse#373]
A minimal reproducing example:
```
In [4]: adj = SparseTensor.from_edge_index(torch.LongTensor([[1,2], [1,3], [2, 3]]))

In [5]: adj.partition(3)
[1]    2709268 bus error (core dumped)  ipython
```
In what circumstances will this partition function lead to core dumping?

**Comment by AaronNing** [comment]
> There exists a few edge cases where METIS sadly silently just crashes :(
> 
> In your case, you need to make sure that your `SparseTensor` is correctly defined, and holds a quadratic matrix:
> 
> ```python
> adj = SparseTensor.from_edge_index(torch.LongTensor([[1,2], [1,3], [2, 3]]).t(), sparse_sizes=(4, 4))
> adj.partition(2)
> ```

Hi, thanks for the reply. What are the "edge cases" which causes METIS "silently just crashes"? I encountered the issue when using a Python package who used the function. It was extremely hard to debug with neither error messgaes nor documents re available. Thanks!

**Comment by rusty1s** [comment]
I think too small graphs is one edge case. The other one is that METIS expects to operate on undirected graphs.
