### ISSUE TITLE
Should coalesce sort the value tensor?

### ISSUE THREAD

**Issue by JoshuaMitton** [rusty1s/pytorch_sparse#39]
I am wonder why the value tensor has not been sorted alongside the index tensor when using coalesce and is this intentional?

My input to coalesce is `edge_index` and `edgebatch` which both for example are:

`edge_index : tensor([[34, 68, 35, 69],
        [35, 69, 34, 68]], device='cuda:0')`

`edgebatch : tensor([34, 67, 67, 34], device='cuda:0')`

Then I call coalesce in the following way:
`edge_index, edgebatch = coalesce(edge_index, edgebatch, num_nodes, num_nodes)`

The output for `edge_index` is as I expected:
`edge_index : tensor([[34, 35, 68, 69],
        [35, 34, 69, 68]], device='cuda:0')`

but the output for edgebatch is not ordered alongside edge_index:
`edgebatch : tensor([34, 67, 67, 34], device='cuda:0')`

Is this intentional or not. Also is it possible to have an option to also sort the value tensor?

**Comment by rusty1s** [comment]
I believe this works as intended, it it just that there is no change in `edgebatch` because only row `35` and `68` gets swapped.

**Comment by JoshuaMitton** [comment]
Yes you're correct, I overlooked what I was inputting.
