### ISSUE TITLE
Failed to import torch_sparse

### ISSUE THREAD

**Issue by ccoulombe** [rusty1s/pytorch_sparse#41]
Pytorch version : `1.4.0`
Pytorch_sparse version: `0.5.1 `
Cuda version : `10.1`
Build torch_sparse: `source`

When importing `torch_sparse` it fails to detect that it was indeed built with CUDA 10.1, as Pytorch.
```
$ python -c "import torch_sparse"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/localscratch/coulombc.5893633.0/.torch/lib/python3.6/site-packages/torch_sparse/__init__.py", line 36, in <module>
    f'Detected that PyTorch and torch_sparse were compiled with '
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.
```
as https://github.com/rusty1s/pytorch_sparse/blob/e78637ea3454965ac3aa35508f5e48d468dd7723/torch_sparse/__init__.py#L23 somehow returns `-1`.

The wheel was built on a host that does not have a GPU card, but the import also fails on a host with GPU device.

**Comment by rusty1s** [comment]
If you want to compile with CUDA support although not having a GPU, you can use the `FORCE_CUDA=1` environment variable. Alternatively, you can just use one of the provided Python wheels for your respective OS/CUDA version (see README).

**Comment by ccoulombe** [comment]
Yes ok thanks! In the previous version, I don't recall needing that env. variable.
But then, `torch_sparse` should work with torch cpu and do not check cuda version.

If not already done, it would be nice/wise to shield all cuda ops like torch does under `.cuda.`.

**Comment by engrAsmasaattar** [comment]
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.

**Comment by wss-xm** [comment]
Pytorch version : 1.4.0+cuda92
Pytorch_sparse version: 0.5.1 
Cuda version : 10.1
I can pip install torch_sparse,but When importing torch_sparse it fails to detect:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 13, in <module>
    '_version', [osp.dirname(__file__)]).origin)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.9.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 22, in <module>
    raise OSError(e)
OSError: libcusparse.so.9.2: cannot open shared object file: No such file or directory

**Comment by wss-xm** [comment]
Please help me ,thank you

**Comment by wss-xm** [comment]
And,torch-scatter torch-cluster torch-spline-conv ，I can succee to import these.I don't know why not to import torch_sparse

**Comment by rluria14** [comment]
@rusty1s also getting this error on the import:

`RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.`

scatter, cluster, and spline-conv seem to be importing fine. sparse is the only that is giving me an error. 

any updates on how to fix this??

**Comment by rusty1s** [comment]
> OSError: libcusparse.so.9.2: cannot open shared object file: No such file or directory

It looks like it is missing `cusparse` which is required for `torch-sparse` usage.

**Comment by lllloda** [comment]
hi guys, I'm having this weird issue
install torch-sparse is fine, but when it comes to import torch_sparse, it comes up with an issue like this:

RuntimeError:
attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
    File "XX/XX/anaconda3/envs/XX/lib/python3.6/site-packages/torch_sparse/storage.py",line145
          def empty(self):
                 self = SparseStorage.__new__(SparseStorage)
                 self._row = None
                 ~~~~~~~~~~~~~ < --- HERE
                 self._rowptr = None
                 self._value = None


so, i checked this storage.py file and everything seems fine, i have also uninstalled torch-sparse and re install it for many times.

emmmm, anyone know what is happening?

**Comment by rusty1s** [comment]
Which PyTorch version are you using?

**Comment by lllloda** [comment]
> Which PyTorch version are you using?

1.8.0a0，compiled from source

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/2146.
