### ISSUE TITLE
what happens when the index is out of size (m, n) ?

### ISSUE THREAD

**Issue by oneliey** [rusty1s/pytorch_sparse#47]
like this one
```python
index = torch.tensor([[1, 1, 3, 0, 2, 1],
                      [0, 3, 1, 1, 0, 2]])
value = torch.tensor([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]])

index, value = coalesce(index, value, m=4, n=2)
```

**Comment by rusty1s** [comment]
Then the output of the method is not well-defined and can be wrong.

**Comment by Oneliey** [comment]
thanks！Does it need to check when this is happening?

**Comment by rusty1s** [comment]
`torch-sparse` does not perform any checks here. It expects you to input the correct values. If you do not have those, you can always pass `m = index[0].max().item() + 1` and `n = index[1].max().item() + 1` as input.

**Comment by Oneliey** [comment]
Need `torch-sparse` to provide checking later?
