### ISSUE TITLE
Cannot import torch.sparse.SparseTensor

### ISSUE THREAD

**Issue by pandasamanvaya** [rusty1s/pytorch_sparse#51]
While performing:-
import torch
import torch_sparse.SparseTensor as sparse

I get the following error:- 
ModuleNotFoundError                      Traceback (most recent call last)
<ipython-input-47-8372058aebf0> in <module>
      1 import torch
----> 2 import torch_sparse.SparseTensor as sparse`

ModuleNotFoundError: No module named 'torch_sparse.SparseTensor'

I am using pytorch==1.3.1, pytorch-sparse==0.4.4

**Comment by rusty1s** [comment]
`torch_sparse.SparseTensor` is only available in >= 0.5.1
