### ISSUE TITLE
Can metis be used in weighted graph ?

### ISSUE THREAD

**Issue by wjlpku** [rusty1s/pytorch_sparse#54]
Hi, I wonder whether metis in pytorch_sparse can be used in a weighted graph, and when I read code metis.py, I can not find anything about edge_attribute, while the cluster_gcn of pytorch_geometric has write the code about edge_attribute in data/cluster.py

**Comment by rusty1s** [comment]
The metis algorithm does not support edge weights. The `edge_attr` in PyG refers to filtering the edge features based on the subgraph metis produced.

**Comment by wjlpku** [comment]
Thanks for your reply.  
Do you have any suggestions for introducing metis into pyG to deal with weighted graphs? Because metis can handle weighted graphs, however, I did not find the interface in torch_sparse to call metis with the input edges and weights of edges.

**Comment by wjlpku** [comment]
Also, I want to know where to find the code about  torch.ops.torch_sparse**.random_walk** or torch.ops.torch_saprse.**metis** in 
`return torch.ops.torch_sparse.random_walk(rowptr, col, start, walk_length)`

**Comment by rusty1s** [comment]
You can find the `metis` call [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/metis_cpu.cpp). If you want to integrate edge weights into the call, please feel free to do so. You are invited to send a PR :)

**Comment by bwdeng20** [comment]
I've integrated `adjwgt`  into `pytorch_sparse` in spite of  lack of experience of `cpp, python` mixed development, but only tested it on `Ubuntu18LTS`. Should I modify the `README` before sending a PR?

**Comment by wjlpku** [comment]
Thanks for your suggestion, I will try it~

**Comment by Ishitori** [comment]
Just want to ask if this has been implemented? Can I use edge weights to do balanced partitioning with METIS? Is there an example? @rusty1s

**Comment by rusty1s** [comment]
Not yet, still looking for some contributor to take upon this part.
