### ISSUE TITLE
reshape

### ISSUE THREAD

**Issue by mariogeiger** [rusty1s/pytorch_sparse#59]
Hi,
This repository is great! I just discovered it and I would like to use it.

Is there an equivalent of `torch.Tensor.reshape` implemented for `SparseTensor`?
A function that would do the folowing operation:

```python
def spreshape(sp, ncol):
    """
    reshape a sparse matrix
    """
    row, col, val = sp.coo()
    index = row * sp.size(1) + col
    return SparseTensor(
        row=index // ncol,
        col=index % ncol,
        value=val
    )
```

PS What does the function `sparse_resize` do? Obviously not what I want^^

**Comment by rusty1s** [comment]
`sparse_resize` should be used when one wants to change the size of the matrix without changing its indices, e.g., to go from a [2, 2] matrix to a [5, 5] matrix. Your function seems to implement `view`. Do you want to submit this as a PR? Looking forward to it.

**Comment by mariogeiger** [comment]
Sure !

**Comment by mariogeiger** [comment]
I have a conceptual question. Why do you represent a sparse matrix as `(row, col, val, m, n)` and not as `(index, val, shape)` where `index` would be the positions in the flattened tensor and `shape` is arbitrary.

I guess there is some optimization gain of having `row` and `col` already there but
```
row = index // shape[1]
col = index % shape[1]
```
does not look so expensive.

**Comment by rusty1s** [comment]
You just want to save `index` of the flattened tensor? Sure, one could do that, but it would require repeated computations of `row` and `col` without many other benefits (expect for easier reshape). Most functionality relies on the `row/rowptr`, `col` format anyway, e.g., slicing, matrix multiplication, ...

**Comment by mariogeiger** [comment]
It would allow sparse tensors of any shape (for instance `[3, 3, 3]`)

**Comment by rusty1s** [comment]
I fully agree, and this might be something to consider in the future. Thanks for the pointer! For now, this repo focuses on fast implementations on tensors with 2 sparse dimensions since more sparse dimensions are mostly synthetic sugar anyway.
