### ISSUE TITLE
use sparse tensor to get each node's neighbors

### ISSUE THREAD

**Issue by Elizabeth1997** [rusty1s/pytorch_sparse#65]
Hi @rusty1s , about using sparse tensor multiplication to implement sage convolution `adj.matmul(x, reduce='mean')`, is it possible for me to get each node's neighbors' feature vectors instead of reduced one? Just like the `message(self, x_j)` function but based on sparse tensor rather than edge index.

**Comment by bwdeng20** [comment]
You can easily get  the neighbors of one node  in the following way.
```python3
import torch
from torch_sparse import SparseStorage
t=th.arange(3*3).view(3,3)
t1=t+t.t()
a1=SparseTensor.from_dense(t1)
# graph constructed
rowptr,col,wgt =a1.csr()
u=2
nbrs= col[ rowptr[u]: rowptr[u+1]]
print(nbrs)
print(t1)
```

**Comment by Elizabeth1997** [comment]
> You can easily get the neighbors of one node in the following way.
> 
> ```python
> import torch
> from torch_sparse import SparseStorage
> t=th.arange(3*3).view(3,3)
> t1=t+t.t()
> a1=SparseTensor.from_dense(t1)
> # graph constructed
> rowptr,col,wgt =a1.csr()
> u=2
> nbrs= col[ rowptr[u]: rowptr[u+1]]
> print(nbrs)
> print(t1)
> ```

Many thanks for answering!
