### ISSUE TITLE
Indexing with arbitrary iterables

### ISSUE THREAD

**Issue by klicperajo** [rusty1s/pytorch_sparse#71]
Support for indexing with arbitrary lists of indices would be very nice, like it is supported by PyTorch, Numpy, scipy.sparse, etc.

Also, the line

https://github.com/rusty1s/pytorch_sparse/blob/049416bcd157b079d744d3d1b458a5ee10bf3434/torch_sparse/tensor.py#L436

forces the usage of a tuple for indexing. It would be nice to make this more general and support e.g. a `list`.

**Comment by rusty1s** [comment]
Hi Johannes, I hope you are well :)

You are right that indexing like `mat[[0, 1, 2, 3]]` is currently not supported. However, the `isinstance(index, tuple)` check is not related to that, and purely checks whether one wants to index across multiple dimensions. For example, for `mat[:10, :10]`, the `index` argument of `__getitem__` will be of type tuple.

Nonetheless, I can easily add indexing via Python lists by converting them to PyTorch tensors first.

**Comment by rusty1s** [comment]
Done, see https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/tensor.py#L445-L446.

**Comment by rusty1s** [comment]
Note that this does only support 1-dimensional lists. I will add support for multi-dimensional lists to my TODO :)

**Comment by klicperajo** [comment]
I'm good, I hope you are too! Great work with the new optimized PyG and the improved DGL datasets, btw!

1-dimensional lists was exactly the use case I had. Thank you! :)
