### ISSUE TITLE
.mean() method behaves like .sum() when dim=1

### ISSUE THREAD

**Issue by Kqiii** [rusty1s/pytorch_sparse#76]
Hi, 

I find that for the ogbn-proteins dataset (please see https://github.com/snap-stanford/ogb/blob/5eabc7aada62fd2bc94c41136500a073235deeca/examples/nodeproppred/proteins/gnn.py#L126), the .mean() method of a torch_sparse.tensor.SparseTensor object behaves just like a .sum() method when dim=1.

The following screenshot shows basic information about this dataset:
![image](https://user-images.githubusercontent.com/38380341/88255073-f189af00-cce9-11ea-8b19-73d3c7979873.png)

The obgn-proteins dataset contains 132,534 nodes and 39,561,252 edges. Every single edge has a feature vector of dimension 8.  We can see that the data.adj_t tensor is symmetric, therefore data.adj_t.mean(dim=0) and data.adj_t.mean(dim=1) are expected to give the same results. But they are different:
![image](https://user-images.githubusercontent.com/38380341/88255332-afad3880-ccea-11ea-8145-35111dada878.png)

However, data.adj_t.sum(dim=0) and data.adj_t.sum(dim=1) indeed give the same results:
<img width="767" alt="Screen Shot 2020-07-23 at 1 46 54 PM" src="https://user-images.githubusercontent.com/38380341/88255437-fef36900-ccea-11ea-9ca6-02806965a086.png">

Please also note that data.adj_t.mean(dim=0) behaves just like data.adj_t.sum(dim=0), yet  data.adj_t.mean(dim=1) and data.adj_t.sum(dim=0) are different (as expected).

Is there anything wrong with my code?

Thanks!

**Comment by rusty1s** [comment]
Thanks for reporting. There was indeed an issue when reducing in dimension 0 (it always used sum). I‘m sorry! It‘s fixed in master now, and I will create a new release ASAP.

**Comment by Kqiii** [comment]
> Thanks for reporting. There was indeed an issue when reducing in dimension 0 (it always used sum). I‘m sorry! It‘s fixed in master now, and I will create a new release ASAP.

Thank you very much for your reply and help!
