### ISSUE TITLE
OSError: .../torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by zhenwang9102** [rusty1s/pytorch_sparse#77]
Will torch_sparse be compatible with PyTorch 1.6.0? Thanks!

**Comment by rusty1s** [comment]
As far as I know, it is already compatible with PyTorch 1.6, but currently needs installation from source. I‘m working on providing the wheels though :)

**Comment by zhenwang9102** [comment]
I see. Really appreciate your efforts! 

I've tried to install torch_sparse from the source and when I import the package, I got the following error:
```
pytorch_sparse/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```
Any idea to solve this problem? Thanks a lot!

**Comment by ThorpeJosh** [comment]
I can second this. I get the OSError trying to import torch_geometric when using a 1.6 wheel for geometric but the 1.5 wheel for sparse.
When i change to building sparse from source using 'pip install torch-sparse' I get the following error,

`RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 0.0`

I am using the nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 docker image and the nvidia-container-runtime to build.
Is there a way to build sparse from source for pytorch 1.6 and cuda 10.x?

**Comment by rusty1s** [comment]
Well, I‘m in the process of providing all wheels for the latest PyTorch release, but you can always install from source. Your error message suggests that the CUDA installation failed, so you should check for that in the logs.

**Comment by linzhk** [comment]
> I see. Really appreciate your efforts!
> 
> I've tried to install torch_sparse from the source and when I import the package, I got the following error:
> 
> ```
> pytorch_sparse/torch_sparse/__init__.py", line 13, in <module>
>     library, [osp.dirname(__file__)]).origin)
> AttributeError: 'NoneType' object has no attribute 'origin'
> ```
> 
> Any idea to solve this problem? Thanks a lot!

i get this problem too. would someone help?

**Comment by rusty1s** [comment]
This is usually casued in case the CPU/CUDA kernels have not been properly built. You can check that by verifying that the `*.so` files exist in `pytorch_sparse/torch_sparse/`, e.g., `_spmm.so`.

**Comment by Anwar-Said** [comment]
I am getting the same error: AttributeError: 'NoneType' object has no attribute 'origin' while importing torch_geometric. I checked *.so file as mentioned in torch_sparse and there is no _spmm.so file. This means my CUDA kernel has not been properly built as mentioned. I did install the Cuda toolkit 11 with torch by following installation guide from https://pytorch.org. Following the installation guide of torch geometric, all the desired packages have been successfully installed without any error. But still, I am having a problem. Could you please help me how can I fix this. I am using Linux (Ubuntue 20.04) with CUDA 11.1. Thanks
