### ISSUE TITLE
RuntimeError: CUDA error: PTX JIT compiler library not found

### ISSUE THREAD

**Issue by violafanfani** [rusty1s/pytorch_sparse#78]
I am trying to run the GNN example for ogbl-ddi link prediction, however I keep running into this error (after reinstalling the conda environment multiple times). I am not sure it's a problems of torch_sparse, however any idea on what might trigger this? The analysis of the cora dataset with the GCN model of PyG works on cuda in the same environment.

```
...
  File "<miniconda>/envs/gnn/lib/python3.8/site-packages/torch_sparse/diag.py", line 41, in set_diag
    inv_mask = ~mask
RuntimeError: CUDA error: PTX JIT compiler library not found
```

**Comment by Tismoney** [comment]
I recommend to check your version `nvidia` compilator (`nvcc --version`). 
And then reinstall your `pytorch` with specific version ([this issue](https://github.com/pytorch/pytorch/issues/21004#issuecomment-496517101) can help)

------------------------------------------------

For example, for me:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

Despite of I have cuda version is `10.2` I reinstall `torch` and `torch_geometrics` with simple script:
```(bash)
CUDA='cu101'
TORCH_V='1.6.0'

pip install torch==$TORCH_V -f https://download.pytorch.org/whl/$CUDA/torch_stable.html
pip install torch-scatter==latest+$CUDA -f https://pytorch-geometric.com/whl/torch-$TORCH_V.html
pip install torch-sparse==latest+$CUDA -f https://pytorch-geometric.com/whl/torch-$TORCH_V.html
pip install torch-cluster==latest+$CUDA -f https://pytorch-geometric.com/whl/torch-$TORCH_V.html
pip install torch-spline-conv==latest+$CUDA -f https://pytorch-geometric.com/whl/torch-$TORCH_V.html
pip install torch-geometric
```
And run `./install_torch_geo.sh`
