### ISSUE TITLE
batch matrix multiplication

### ISSUE THREAD

**Issue by speedcell4** [rusty1s/pytorch_sparse#8]
any idea about how to implement batch matrix multiplication (`batch_sparse_matmul`)? thanks~

```python
a = torch.rand(10, 4, 5).to_sparse()
b = torch.rand(10, 5, 6)
assert batch_sparse_matmul(a, b).size() == (10, 4, 6)
```

**Comment by rusty1s** [comment]
Hi and sorry for being late,

The only workaround I know about is to convert your sparse tensor `a` into block-diagonal form (shape: `[40, 50]`) and stack `b` vertically (shape: `[50, 6]).
Then the normal `matmul` op can be used, resulting in shape `[40, 6]` and reshape to `[10, 4, 6]`.
However, the converting to a block-diagonal form needs a custom op.

**Comment by mpariente** [comment]
Sorry to bother, but I saw you perform the mini-batching like this in `pytorch-geometric` and I wonder, do you have a pointer to this custom op? Or something close to it?
