### ISSUE TITLE
SPMM in batch 

### ISSUE THREAD

**Issue by yjhong89** [rusty1s/pytorch_sparse#80]
Hello. I am YJ Hong.

I wonder Sparse Dense Matrix Multiplication (spmm) works in batch mode.

I like to calculate 'spmm' with fixed (index, value, m, m) sparse set and matrix have shape of (batch size, m, num features)

Of course, it is possible that doing 'spmm' for every element in a batch and stack them by for loop, but I wonder if there is a more nice way to do that.

Thanks in advance.
Regards,
YJ Hong.

**Comment by rusty1s** [comment]
Yes, you can already do this, *e.g.*,
```
x = torch.randn(batch_size, num_nodes, num_features]
adj = Sparsetensot.from_eye(num_nodes, num_nodes)

x @ adj
```

**Comment by yjhong89** [comment]
@rusty1s 
Thanks. I will try.

**Comment by shi27feng** [comment]
Hi @rusty1s,
In order to support 3D tensor: e.g., the dimension of (L, N, C), L graphs share the same topology, i.e., adjacency matrix but with different nonzero values, e.g., the dimension of (L, num_edges), I just made a minor modification on your code

```python
def _spmm(indices, nz, m, n, d):
    """
    :argument
        indices (:class: `LongTensor`): tensor of indices of sparse matrix.
        nz (:class: `Tensor`): tensor of nonzero of sparse matrix.
        m (int): The first dimension of corresponding dense matrix.
        n (int): The second dimension of corresponding dense matrix.
        d (:class:`Tensor`): tensor of dense matrix
    """
    assert n == d.shape[-2]
    rows, cols = indices
    d = d if d.dim() > 1 else d.unsqueeze(-1)
    out = d[..., cols, :] * nz.unsqueeze(-1)
    return scatter_add(out, rows, dim=-2, dim_size=m)
```
Thanks for the enlightenment of your original code :)

**Comment by ftmtk** [comment]
> Yes, you can already do this using `SparseTensor` (still undocumented), _e.g._,
> 
> ```
> x = torch.randn(batch_size, num_nodes, num_features]
> adj = Sparsetensot.from_eye(num_nodes, num_nodes)
> 
> x @ adj
> ```

Does the `adj` has to be node-to-node adjacent matrix? I was wondering if the same think works for an edge-to-node matrix, i.e. n_cols != n_rows.

**Comment by rusty1s** [comment]
The sparse matrix does not need to be quadratic.

**Comment by ftmtk** [comment]
Thanks! 

Just pasting my sample code here in case anyone would like to give it a go.

``` python
batch, card_v, card_e, df = 4, 1024, 2048, 32
density = 1 / 500
nnz = int(card_v * card_e * density)
e2n_mat = torch.zeros(card_v * card_e)
e2n_mat[:nnz] = torch.randn(nnz)
e2n_mat = e2n_mat[torch.randperm(card_v * card_e)]
e2n_mat = e2n_mat.view(card_v, card_e)

scm_e2n_mat = e2n_mat.to_sparse().coalesce()
row_scm = scm_e2n_mat._indices()[0]
col_scm = scm_e2n_mat._indices()[1]

print(scm_e2n_mat._indices().size())

ts_e2n_mat = torch_sparse.SparseTensor(row=row_scm, col=col_scm, value=scm_e2n_mat._values(),
                                       sparse_sizes=scm_e2n_mat.size())

dense_tensor = torch.randn([batch, card_e, df])

h = ts_e2n_mat @ dense_tensor

print(h.size())

```
