### ISSUE TITLE
how to create a sparse tensor from numpy array with size of (n_samples, n_nodes, n_nodes) directly?

### ISSUE THREAD

**Issue by Boltzmachine** [rusty1s/pytorch_sparse#84]

**Comment by rusty1s** [comment]
There is a method called `SparseTensor.from_dense`, but it expects two-dimensional tensors as input.

**Comment by Boltzmachine** [comment]
So could you recommend a way to transform  numpy 2D array in batch

**Comment by rusty1s** [comment]
Not exactly sure what you mean. Can you elaborate?

**Comment by Boltzmachine** [comment]
Oh, I've got it! Thanks for your beautiful work!
