### ISSUE TITLE
OSError: /opt/conda/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by mckhang** [rusty1s/pytorch_sparse#85]
Hi, using CUDA10.2 with pytorch 1.5.0 here. I ran the following command:

pip install torch-scatter==latest+cu102 torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html

and the installations ran successfully. 

However, when I tried out the script:

import torch
from torch_sparse import coalesce

I get the following error:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-67fbdbf36bb6> in <module>
      1 import torch
----> 2 from torch_sparse import coalesce

/opt/conda/lib/python3.6/site-packages/torch_sparse/__init__.py in <module>
     11 ]:
     12     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
---> 13         library, [osp.dirname(__file__)]).origin)
     14 
     15 if torch.cuda.is_available() and torch.version.cuda:  # pragma: no cover

/opt/conda/lib/python3.6/site-packages/torch/_ops.py in load_library(self, path)
    103             # static (global) initialization code in order to register custom
    104             # operators with the JIT.
--> 105             ctypes.CDLL(path)
    106         self.loaded_libraries.add(path)
    107 

/opt/conda/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /opt/conda/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Any way to get around this?

**Comment by rusty1s** [comment]
This error usually indicates that CUDA and PyTorch versions do not match, and can be caused by multiple PyTorch or multiple CUDA installations. Hopefully, https://github.com/rusty1s/pytorch_geometric/issues/999 is useful to you.

**Comment by mckhang** [comment]
Hi, thank you for your reply. I have managed to get it working by installing on a container environment with pip install torch-scatter and then pip install torch-sparse. Thanks

**Comment by LukeLIN-web** [comment]
I find that I uninstall torch1.9 and install torch1.10, it still happen. So the torch-sparse have to match the torch version. install and uninstall with torch.
