### ISSUE TITLE
Ubuntu20.4 CUDA11.0; Detected that PyTorch and torch_sparse were compiled with different CUDA versions. 

### ISSUE THREAD

**Issue by JerryYan97** [rusty1s/pytorch_sparse#86]
Hi, 
I installed both pytorch and pytorch-sparse in CUDA10.2 version.
But it looks like CUDA10.2 doesn't support the latest version of Ubuntu.
Is there any solution to this problem?
Thanks!

RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.1. Please reinstall the torch_sparse that matches your PyTorch install.

**Comment by rusty1s** [comment]
Did you install torch-sparse via binaries or by compiling from source? It looks like you have a CUDA 11 toolkit installed, and that causes inconsistencies when loading.

**Comment by JerryYan97** [comment]
Oh nope. I think I fix this problem by just degrading the current CUDA to 10.2.
It looks like it also needs a gcc degrade to 7.0, which I forgot to do and caused CUDA10.2 installation fail.
Thanks!
