### ISSUE TITLE
Upload wheels on PyPi

### ISSUE THREAD

**Issue by mpariente** [rusty1s/pytorch_sparse#88]
Hi Matthias, 

Just wondering, are you uploading the wheels on PyPI when you publish `torch_sparse`? 

Wheels are pretty long to build when we install from pip (more than a minute) and I wondered if you could upload them when you make a release? That'd be great. 

The only thing to do is to add `bdist_wheel` when making the dist.  
```bash
rm -rf ./dist/*
python setup.py sdist bdist_wheel
twine upload dist/*
```

Thanks ;-)

**Comment by rusty1s** [comment]
No, wheels are not uploaded to PyPI since different CUDA versions require different wheels (which is not covered by PyPI).

**Comment by mpariente** [comment]
Ok, I thought there was a reason ^^ 
Thanks for your answer !
