### ISSUE TITLE
Segmentation fault in GPU sparse matrix by sparse matrix product 

### ISSUE THREAD

**Issue by amkatrutsa** [rusty1s/pytorch_sparse#9]
Hello!
Thanks a lot for this PyTorch extension!
But I faced with the following issue. I tried to run an example of sparse matrix by sparse matrix product from README.md, but on GPU, and get "Segmentation fault" error. Below is the code of my short script to reproduce error.
```python
import torch
from torch_sparse import spspmm
device = torch.device("cuda")

indexA = torch.tensor([[0, 0, 1, 2, 2], [1, 2, 0, 0, 1]], device=device)
valueA = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float, device=device)

indexB = torch.tensor([[0, 2], [1, 0]], device=device)
valueB = torch.tensor([2, 4], dtype=torch.float, device=device)

indexC, valueC = spspmm(indexA, valueA, indexB, valueB, 3, 3, 2)
```
I use PyTorch 1.0, CUDA 8.0 and install both extensions (pytorch_scatter and pytorch_sparse) from source files in repositories.

**Comment by rusty1s** [comment]
Interesting. I do not have a segmentation fault when running your script. Currently using PyTorch 1.0 with CUDA 10. Any chance you can further debug?

**Comment by amkatrutsa** [comment]
Well, I run test script for ```pytorch_scatter``` as it is described in README, but it also fails with segmentatiuon fault error without any additional messages. How can I get more detailed report? May be with some additional compiler options?

**Comment by rusty1s** [comment]
I think your best bet is to comment out lines in [spspmm_kernel.cu](https://github.com/rusty1s/pytorch_sparse/blob/master/cuda/spspmm_kernel.cu) to find the line which causes the problems.

**Comment by insuhan** [comment]
I also have a segmentation fault when running the above code (with cuda data type). I run the code using PyTorch 1.0 and CUDA 8.0. probably, this problem is related to CUDA version.

**Comment by rusty1s** [comment]
I will try to reproduce the error on a CUDA 8 machine.

**Comment by rusty1s** [comment]
Still not reproducible on CUDA v8.0.61, PyTorch 1.0.0, Ubuntu 16.04 :(
What GPUs are you using?

**Comment by eudoraxj** [comment]
I have the same problem, did you solve it?

**Comment by amkatrutsa** [comment]
I used Tesla K80, Ubuntu 14.04.5 LTS.

**Comment by lgray** [comment]
Hi! I have the same issue with a Telsa P100, running the same code as in the issue description.

I'm using:
- torch_sparse 0.2.4
- pytorch 1.0.1.post2
- nvidia driver version 396.24
- Cuda compilation tools, release 9.0, V9.0.176

**Comment by lgray** [comment]
OK - I've solved this particular issue it seems, generally by recompiling everything... Which is not an optimal or descriptive solution. Anyway, got it working.

Now to understand why I'm getting `an illegal memory access was encountered` later...

**Comment by ekagra-ranjan** [comment]
Did anyone find any solution?
 I am also facing this issue. The exact error is :
```
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp:383
```
The error occurs randomly after a few iterations.

**Comment by ekagra-ranjan** [comment]
@rusty1s I want to try commenting out the lines and printing values as you suggested in your [comment](https://github.com/rusty1s/pytorch_sparse/issues/9#issuecomment-464040890). After commenting some lines how do I recomplie `torch_sparse` so that I can figure out the lines which are causing the trouble?

**Comment by rusty1s** [comment]
You can recompile via python setup.py install or python setup.py test. In case it does not recompile the kernels, try deleting the build/ directory.

**Comment by ekagra-ranjan** [comment]
According to you what would be the best way to output on terminal or see the values of the intermediate values in the kernel?

**Comment by ekagra-ranjan** [comment]
I am using printf statement [`printf("i:%d j:%d\n", i, j);`] for viewing the intermediate values. When I run `python setup.py test`, the print statements outputs the value on the terminal. But when I run the following, I do not see the outputs from printf on the terminal:
```
import torch
from torch_sparse import spspmm

indexA = torch.tensor([[0, 0, 1, 2, 2], [1, 2, 0, 0, 1]])
valueA = torch.Tensor([1, 2, 3, 4, 5])

indexB = torch.tensor([[0, 2], [1, 0]])
valueB = torch.Tensor([2, 4])

indexC, valueC = spspmm(indexA.cuda(), valueA.cuda(), indexB.cuda(), valueB.cuda(), 3, 3, 2)  
```

Any suggestions as to how can I see the intermediate values when running my code?

**Comment by zhenhuascut** [comment]
I found the reason for Segmentation fault. It occurs when you use a lower version compile to install the package even though it is successful. Try to use a new version to install it. e.g. scl enable devtoolset-7 bash.
