### ISSUE TITLE
Interface to torch_sparse_solve

### ISSUE THREAD

**Issue by mpariente** [rusty1s/pytorch_sparse#93]
Hey!

You might not have seen this [torch_sparse_solve](https://github.com/flaport/torch_sparse_solve) repo, and thought you'd be interested if you didn't. 

I opened an issue to support `SparseTensor` [over there](https://github.com/flaport/torch_sparse_solve/issues/4).

**Comment by rusty1s** [comment]
Thanks for letting me know. This is pretty interesting. In theory, you can use `torch_sparse_solve` with `SparseTensor` by transforming to a `torch.sparse_coo_tensor` first:
```python
A = SparseTensor(...)
x = solve(A.to_torch_sparse_coo_tensor, b)
```
 One caveat is though that `SparseTensor` currently only supports two sparse dimensions (so you lose out on the batching capabilities).

**Comment by mpariente** [comment]
I already do that. Treat the sparse matrix as block diagonal, convert to coo_tensor, add a dummy dimension. It works perfectly !

Plus, the batching capability is currently a for loop so `torch_sparse`'s approach is faster.
