### ISSUE TITLE
sample_adj output

### ISSUE THREAD

**Issue by MortezaRamezani** [rusty1s/pytorch_sparse#94]
It seems like the col tensor in the output of sample_adj is not sorted and it breaks some functions such as **fill_diag** or **coalesce** 
![image](https://user-images.githubusercontent.com/2129613/98490486-a5fb0280-21ff-11eb-9138-04a49d3beed0.png)

**Comment by rusty1s** [comment]
You are right. This is now fixed in `torch-sparse` master.

**Comment by MortezaRamezani** [comment]
I think the same problem exists for saint_subgraph.
