### ISSUE TITLE
Clarification on coalesce

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_sparse#97]
Just a quick question: what exactly are the parameters for `m` and `n` used in for `coalesce`? It isn't apparent to me from the example.

**Comment by rusty1s** [comment]
`m` and `n` denote the sizes of your sparse matrix, i.e., the maximum values of `index[0]` and `index[1]`.

**Comment by vymao** [comment]
Which index does this refer to in the example? `m = 3` and `n = 2` don't seem to correspond to either here?

```
import torch
from torch_sparse import coalesce

index = torch.tensor([[1, 0, 1, 0, 2, 1],
                      [0, 1, 1, 1, 0, 0]])
value = torch.Tensor([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]])

index, value = coalesce(index, value, m=3, n=2)
print(index)
tensor([[0, 1, 1, 2],
        [1, 0, 1, 0]])
print(value)
tensor([[6.0, 8.0],
        [7.0, 9.0],
        [3.0, 4.0],
        [5.0, 6.0]])
```

**Comment by rusty1s** [comment]
```python
index = torch.tensor([[1, 0, 1, 0, 2, 1],
                      [0, 1, 1, 1, 0, 0]])
```
so `index[0].max() + 1 = 3` and `index[1].max() + 1 = 2`.
